package com.mrbt.mvc.model.funds;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Ths035Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public Ths035Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqIsNull() {
            addCriterion("SEQ is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(BigDecimal value) {
            addCriterion("SEQ =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(BigDecimal value) {
            addCriterion("SEQ <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(BigDecimal value) {
            addCriterion("SEQ >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SEQ >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(BigDecimal value) {
            addCriterion("SEQ <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SEQ <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<BigDecimal> values) {
            addCriterion("SEQ in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<BigDecimal> values) {
            addCriterion("SEQ not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEQ between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEQ not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035IsNull() {
            addCriterion("CTIME_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035IsNotNull() {
            addCriterion("CTIME_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035EqualTo(Date value) {
            addCriterion("CTIME_THS035 =", value, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035NotEqualTo(Date value) {
            addCriterion("CTIME_THS035 <>", value, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035GreaterThan(Date value) {
            addCriterion("CTIME_THS035 >", value, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035GreaterThanOrEqualTo(Date value) {
            addCriterion("CTIME_THS035 >=", value, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035LessThan(Date value) {
            addCriterion("CTIME_THS035 <", value, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035LessThanOrEqualTo(Date value) {
            addCriterion("CTIME_THS035 <=", value, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035In(List<Date> values) {
            addCriterion("CTIME_THS035 in", values, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035NotIn(List<Date> values) {
            addCriterion("CTIME_THS035 not in", values, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035Between(Date value1, Date value2) {
            addCriterion("CTIME_THS035 between", value1, value2, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andCtimeThs035NotBetween(Date value1, Date value2) {
            addCriterion("CTIME_THS035 not between", value1, value2, "ctimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035IsNull() {
            addCriterion("RTIME_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035IsNotNull() {
            addCriterion("RTIME_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035EqualTo(Date value) {
            addCriterion("RTIME_THS035 =", value, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035NotEqualTo(Date value) {
            addCriterion("RTIME_THS035 <>", value, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035GreaterThan(Date value) {
            addCriterion("RTIME_THS035 >", value, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035GreaterThanOrEqualTo(Date value) {
            addCriterion("RTIME_THS035 >=", value, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035LessThan(Date value) {
            addCriterion("RTIME_THS035 <", value, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035LessThanOrEqualTo(Date value) {
            addCriterion("RTIME_THS035 <=", value, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035In(List<Date> values) {
            addCriterion("RTIME_THS035 in", values, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035NotIn(List<Date> values) {
            addCriterion("RTIME_THS035 not in", values, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035Between(Date value1, Date value2) {
            addCriterion("RTIME_THS035 between", value1, value2, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andRtimeThs035NotBetween(Date value1, Date value2) {
            addCriterion("RTIME_THS035 not between", value1, value2, "rtimeThs035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035IsNull() {
            addCriterion("F001_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF001Ths035IsNotNull() {
            addCriterion("F001_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF001Ths035EqualTo(String value) {
            addCriterion("F001_THS035 =", value, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035NotEqualTo(String value) {
            addCriterion("F001_THS035 <>", value, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035GreaterThan(String value) {
            addCriterion("F001_THS035 >", value, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F001_THS035 >=", value, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035LessThan(String value) {
            addCriterion("F001_THS035 <", value, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035LessThanOrEqualTo(String value) {
            addCriterion("F001_THS035 <=", value, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035Like(String value) {
            addCriterion("F001_THS035 like", value, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035NotLike(String value) {
            addCriterion("F001_THS035 not like", value, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035In(List<String> values) {
            addCriterion("F001_THS035 in", values, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035NotIn(List<String> values) {
            addCriterion("F001_THS035 not in", values, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035Between(String value1, String value2) {
            addCriterion("F001_THS035 between", value1, value2, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF001Ths035NotBetween(String value1, String value2) {
            addCriterion("F001_THS035 not between", value1, value2, "f001Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035IsNull() {
            addCriterion("F002_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF002Ths035IsNotNull() {
            addCriterion("F002_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF002Ths035EqualTo(String value) {
            addCriterion("F002_THS035 =", value, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035NotEqualTo(String value) {
            addCriterion("F002_THS035 <>", value, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035GreaterThan(String value) {
            addCriterion("F002_THS035 >", value, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F002_THS035 >=", value, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035LessThan(String value) {
            addCriterion("F002_THS035 <", value, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035LessThanOrEqualTo(String value) {
            addCriterion("F002_THS035 <=", value, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035Like(String value) {
            addCriterion("F002_THS035 like", value, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035NotLike(String value) {
            addCriterion("F002_THS035 not like", value, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035In(List<String> values) {
            addCriterion("F002_THS035 in", values, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035NotIn(List<String> values) {
            addCriterion("F002_THS035 not in", values, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035Between(String value1, String value2) {
            addCriterion("F002_THS035 between", value1, value2, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF002Ths035NotBetween(String value1, String value2) {
            addCriterion("F002_THS035 not between", value1, value2, "f002Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035IsNull() {
            addCriterion("F003_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF003Ths035IsNotNull() {
            addCriterion("F003_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF003Ths035EqualTo(String value) {
            addCriterion("F003_THS035 =", value, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035NotEqualTo(String value) {
            addCriterion("F003_THS035 <>", value, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035GreaterThan(String value) {
            addCriterion("F003_THS035 >", value, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F003_THS035 >=", value, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035LessThan(String value) {
            addCriterion("F003_THS035 <", value, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035LessThanOrEqualTo(String value) {
            addCriterion("F003_THS035 <=", value, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035Like(String value) {
            addCriterion("F003_THS035 like", value, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035NotLike(String value) {
            addCriterion("F003_THS035 not like", value, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035In(List<String> values) {
            addCriterion("F003_THS035 in", values, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035NotIn(List<String> values) {
            addCriterion("F003_THS035 not in", values, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035Between(String value1, String value2) {
            addCriterion("F003_THS035 between", value1, value2, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF003Ths035NotBetween(String value1, String value2) {
            addCriterion("F003_THS035 not between", value1, value2, "f003Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035IsNull() {
            addCriterion("F004_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF004Ths035IsNotNull() {
            addCriterion("F004_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF004Ths035EqualTo(BigDecimal value) {
            addCriterion("F004_THS035 =", value, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035NotEqualTo(BigDecimal value) {
            addCriterion("F004_THS035 <>", value, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035GreaterThan(BigDecimal value) {
            addCriterion("F004_THS035 >", value, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F004_THS035 >=", value, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035LessThan(BigDecimal value) {
            addCriterion("F004_THS035 <", value, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035LessThanOrEqualTo(BigDecimal value) {
            addCriterion("F004_THS035 <=", value, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035In(List<BigDecimal> values) {
            addCriterion("F004_THS035 in", values, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035NotIn(List<BigDecimal> values) {
            addCriterion("F004_THS035 not in", values, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("F004_THS035 between", value1, value2, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF004Ths035NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F004_THS035 not between", value1, value2, "f004Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035IsNull() {
            addCriterion("F005_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF005Ths035IsNotNull() {
            addCriterion("F005_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF005Ths035EqualTo(Date value) {
            addCriterion("F005_THS035 =", value, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035NotEqualTo(Date value) {
            addCriterion("F005_THS035 <>", value, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035GreaterThan(Date value) {
            addCriterion("F005_THS035 >", value, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035GreaterThanOrEqualTo(Date value) {
            addCriterion("F005_THS035 >=", value, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035LessThan(Date value) {
            addCriterion("F005_THS035 <", value, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035LessThanOrEqualTo(Date value) {
            addCriterion("F005_THS035 <=", value, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035In(List<Date> values) {
            addCriterion("F005_THS035 in", values, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035NotIn(List<Date> values) {
            addCriterion("F005_THS035 not in", values, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035Between(Date value1, Date value2) {
            addCriterion("F005_THS035 between", value1, value2, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF005Ths035NotBetween(Date value1, Date value2) {
            addCriterion("F005_THS035 not between", value1, value2, "f005Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035IsNull() {
            addCriterion("F007_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF007Ths035IsNotNull() {
            addCriterion("F007_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF007Ths035EqualTo(String value) {
            addCriterion("F007_THS035 =", value, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035NotEqualTo(String value) {
            addCriterion("F007_THS035 <>", value, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035GreaterThan(String value) {
            addCriterion("F007_THS035 >", value, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F007_THS035 >=", value, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035LessThan(String value) {
            addCriterion("F007_THS035 <", value, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035LessThanOrEqualTo(String value) {
            addCriterion("F007_THS035 <=", value, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035Like(String value) {
            addCriterion("F007_THS035 like", value, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035NotLike(String value) {
            addCriterion("F007_THS035 not like", value, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035In(List<String> values) {
            addCriterion("F007_THS035 in", values, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035NotIn(List<String> values) {
            addCriterion("F007_THS035 not in", values, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035Between(String value1, String value2) {
            addCriterion("F007_THS035 between", value1, value2, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF007Ths035NotBetween(String value1, String value2) {
            addCriterion("F007_THS035 not between", value1, value2, "f007Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035IsNull() {
            addCriterion("F008_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF008Ths035IsNotNull() {
            addCriterion("F008_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF008Ths035EqualTo(String value) {
            addCriterion("F008_THS035 =", value, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035NotEqualTo(String value) {
            addCriterion("F008_THS035 <>", value, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035GreaterThan(String value) {
            addCriterion("F008_THS035 >", value, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F008_THS035 >=", value, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035LessThan(String value) {
            addCriterion("F008_THS035 <", value, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035LessThanOrEqualTo(String value) {
            addCriterion("F008_THS035 <=", value, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035Like(String value) {
            addCriterion("F008_THS035 like", value, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035NotLike(String value) {
            addCriterion("F008_THS035 not like", value, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035In(List<String> values) {
            addCriterion("F008_THS035 in", values, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035NotIn(List<String> values) {
            addCriterion("F008_THS035 not in", values, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035Between(String value1, String value2) {
            addCriterion("F008_THS035 between", value1, value2, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF008Ths035NotBetween(String value1, String value2) {
            addCriterion("F008_THS035 not between", value1, value2, "f008Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035IsNull() {
            addCriterion("F011_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF011Ths035IsNotNull() {
            addCriterion("F011_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF011Ths035EqualTo(String value) {
            addCriterion("F011_THS035 =", value, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035NotEqualTo(String value) {
            addCriterion("F011_THS035 <>", value, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035GreaterThan(String value) {
            addCriterion("F011_THS035 >", value, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F011_THS035 >=", value, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035LessThan(String value) {
            addCriterion("F011_THS035 <", value, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035LessThanOrEqualTo(String value) {
            addCriterion("F011_THS035 <=", value, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035Like(String value) {
            addCriterion("F011_THS035 like", value, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035NotLike(String value) {
            addCriterion("F011_THS035 not like", value, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035In(List<String> values) {
            addCriterion("F011_THS035 in", values, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035NotIn(List<String> values) {
            addCriterion("F011_THS035 not in", values, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035Between(String value1, String value2) {
            addCriterion("F011_THS035 between", value1, value2, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF011Ths035NotBetween(String value1, String value2) {
            addCriterion("F011_THS035 not between", value1, value2, "f011Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035IsNull() {
            addCriterion("F012_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF012Ths035IsNotNull() {
            addCriterion("F012_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF012Ths035EqualTo(Date value) {
            addCriterion("F012_THS035 =", value, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035NotEqualTo(Date value) {
            addCriterion("F012_THS035 <>", value, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035GreaterThan(Date value) {
            addCriterion("F012_THS035 >", value, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035GreaterThanOrEqualTo(Date value) {
            addCriterion("F012_THS035 >=", value, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035LessThan(Date value) {
            addCriterion("F012_THS035 <", value, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035LessThanOrEqualTo(Date value) {
            addCriterion("F012_THS035 <=", value, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035In(List<Date> values) {
            addCriterion("F012_THS035 in", values, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035NotIn(List<Date> values) {
            addCriterion("F012_THS035 not in", values, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035Between(Date value1, Date value2) {
            addCriterion("F012_THS035 between", value1, value2, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF012Ths035NotBetween(Date value1, Date value2) {
            addCriterion("F012_THS035 not between", value1, value2, "f012Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035IsNull() {
            addCriterion("F013_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF013Ths035IsNotNull() {
            addCriterion("F013_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF013Ths035EqualTo(Date value) {
            addCriterion("F013_THS035 =", value, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035NotEqualTo(Date value) {
            addCriterion("F013_THS035 <>", value, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035GreaterThan(Date value) {
            addCriterion("F013_THS035 >", value, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035GreaterThanOrEqualTo(Date value) {
            addCriterion("F013_THS035 >=", value, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035LessThan(Date value) {
            addCriterion("F013_THS035 <", value, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035LessThanOrEqualTo(Date value) {
            addCriterion("F013_THS035 <=", value, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035In(List<Date> values) {
            addCriterion("F013_THS035 in", values, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035NotIn(List<Date> values) {
            addCriterion("F013_THS035 not in", values, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035Between(Date value1, Date value2) {
            addCriterion("F013_THS035 between", value1, value2, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF013Ths035NotBetween(Date value1, Date value2) {
            addCriterion("F013_THS035 not between", value1, value2, "f013Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035IsNull() {
            addCriterion("F014_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF014Ths035IsNotNull() {
            addCriterion("F014_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF014Ths035EqualTo(String value) {
            addCriterion("F014_THS035 =", value, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035NotEqualTo(String value) {
            addCriterion("F014_THS035 <>", value, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035GreaterThan(String value) {
            addCriterion("F014_THS035 >", value, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F014_THS035 >=", value, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035LessThan(String value) {
            addCriterion("F014_THS035 <", value, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035LessThanOrEqualTo(String value) {
            addCriterion("F014_THS035 <=", value, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035Like(String value) {
            addCriterion("F014_THS035 like", value, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035NotLike(String value) {
            addCriterion("F014_THS035 not like", value, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035In(List<String> values) {
            addCriterion("F014_THS035 in", values, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035NotIn(List<String> values) {
            addCriterion("F014_THS035 not in", values, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035Between(String value1, String value2) {
            addCriterion("F014_THS035 between", value1, value2, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF014Ths035NotBetween(String value1, String value2) {
            addCriterion("F014_THS035 not between", value1, value2, "f014Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035IsNull() {
            addCriterion("F015_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF015Ths035IsNotNull() {
            addCriterion("F015_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF015Ths035EqualTo(String value) {
            addCriterion("F015_THS035 =", value, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035NotEqualTo(String value) {
            addCriterion("F015_THS035 <>", value, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035GreaterThan(String value) {
            addCriterion("F015_THS035 >", value, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F015_THS035 >=", value, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035LessThan(String value) {
            addCriterion("F015_THS035 <", value, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035LessThanOrEqualTo(String value) {
            addCriterion("F015_THS035 <=", value, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035Like(String value) {
            addCriterion("F015_THS035 like", value, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035NotLike(String value) {
            addCriterion("F015_THS035 not like", value, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035In(List<String> values) {
            addCriterion("F015_THS035 in", values, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035NotIn(List<String> values) {
            addCriterion("F015_THS035 not in", values, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035Between(String value1, String value2) {
            addCriterion("F015_THS035 between", value1, value2, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF015Ths035NotBetween(String value1, String value2) {
            addCriterion("F015_THS035 not between", value1, value2, "f015Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035IsNull() {
            addCriterion("F016_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF016Ths035IsNotNull() {
            addCriterion("F016_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF016Ths035EqualTo(String value) {
            addCriterion("F016_THS035 =", value, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035NotEqualTo(String value) {
            addCriterion("F016_THS035 <>", value, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035GreaterThan(String value) {
            addCriterion("F016_THS035 >", value, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F016_THS035 >=", value, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035LessThan(String value) {
            addCriterion("F016_THS035 <", value, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035LessThanOrEqualTo(String value) {
            addCriterion("F016_THS035 <=", value, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035Like(String value) {
            addCriterion("F016_THS035 like", value, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035NotLike(String value) {
            addCriterion("F016_THS035 not like", value, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035In(List<String> values) {
            addCriterion("F016_THS035 in", values, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035NotIn(List<String> values) {
            addCriterion("F016_THS035 not in", values, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035Between(String value1, String value2) {
            addCriterion("F016_THS035 between", value1, value2, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF016Ths035NotBetween(String value1, String value2) {
            addCriterion("F016_THS035 not between", value1, value2, "f016Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035IsNull() {
            addCriterion("F017_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF017Ths035IsNotNull() {
            addCriterion("F017_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF017Ths035EqualTo(String value) {
            addCriterion("F017_THS035 =", value, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035NotEqualTo(String value) {
            addCriterion("F017_THS035 <>", value, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035GreaterThan(String value) {
            addCriterion("F017_THS035 >", value, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F017_THS035 >=", value, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035LessThan(String value) {
            addCriterion("F017_THS035 <", value, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035LessThanOrEqualTo(String value) {
            addCriterion("F017_THS035 <=", value, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035Like(String value) {
            addCriterion("F017_THS035 like", value, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035NotLike(String value) {
            addCriterion("F017_THS035 not like", value, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035In(List<String> values) {
            addCriterion("F017_THS035 in", values, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035NotIn(List<String> values) {
            addCriterion("F017_THS035 not in", values, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035Between(String value1, String value2) {
            addCriterion("F017_THS035 between", value1, value2, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF017Ths035NotBetween(String value1, String value2) {
            addCriterion("F017_THS035 not between", value1, value2, "f017Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035IsNull() {
            addCriterion("F018_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF018Ths035IsNotNull() {
            addCriterion("F018_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF018Ths035EqualTo(String value) {
            addCriterion("F018_THS035 =", value, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035NotEqualTo(String value) {
            addCriterion("F018_THS035 <>", value, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035GreaterThan(String value) {
            addCriterion("F018_THS035 >", value, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F018_THS035 >=", value, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035LessThan(String value) {
            addCriterion("F018_THS035 <", value, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035LessThanOrEqualTo(String value) {
            addCriterion("F018_THS035 <=", value, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035Like(String value) {
            addCriterion("F018_THS035 like", value, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035NotLike(String value) {
            addCriterion("F018_THS035 not like", value, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035In(List<String> values) {
            addCriterion("F018_THS035 in", values, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035NotIn(List<String> values) {
            addCriterion("F018_THS035 not in", values, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035Between(String value1, String value2) {
            addCriterion("F018_THS035 between", value1, value2, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF018Ths035NotBetween(String value1, String value2) {
            addCriterion("F018_THS035 not between", value1, value2, "f018Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035IsNull() {
            addCriterion("F019_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF019Ths035IsNotNull() {
            addCriterion("F019_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF019Ths035EqualTo(String value) {
            addCriterion("F019_THS035 =", value, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035NotEqualTo(String value) {
            addCriterion("F019_THS035 <>", value, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035GreaterThan(String value) {
            addCriterion("F019_THS035 >", value, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F019_THS035 >=", value, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035LessThan(String value) {
            addCriterion("F019_THS035 <", value, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035LessThanOrEqualTo(String value) {
            addCriterion("F019_THS035 <=", value, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035Like(String value) {
            addCriterion("F019_THS035 like", value, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035NotLike(String value) {
            addCriterion("F019_THS035 not like", value, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035In(List<String> values) {
            addCriterion("F019_THS035 in", values, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035NotIn(List<String> values) {
            addCriterion("F019_THS035 not in", values, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035Between(String value1, String value2) {
            addCriterion("F019_THS035 between", value1, value2, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF019Ths035NotBetween(String value1, String value2) {
            addCriterion("F019_THS035 not between", value1, value2, "f019Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035IsNull() {
            addCriterion("F020_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF020Ths035IsNotNull() {
            addCriterion("F020_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF020Ths035EqualTo(String value) {
            addCriterion("F020_THS035 =", value, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035NotEqualTo(String value) {
            addCriterion("F020_THS035 <>", value, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035GreaterThan(String value) {
            addCriterion("F020_THS035 >", value, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F020_THS035 >=", value, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035LessThan(String value) {
            addCriterion("F020_THS035 <", value, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035LessThanOrEqualTo(String value) {
            addCriterion("F020_THS035 <=", value, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035Like(String value) {
            addCriterion("F020_THS035 like", value, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035NotLike(String value) {
            addCriterion("F020_THS035 not like", value, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035In(List<String> values) {
            addCriterion("F020_THS035 in", values, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035NotIn(List<String> values) {
            addCriterion("F020_THS035 not in", values, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035Between(String value1, String value2) {
            addCriterion("F020_THS035 between", value1, value2, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF020Ths035NotBetween(String value1, String value2) {
            addCriterion("F020_THS035 not between", value1, value2, "f020Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035IsNull() {
            addCriterion("F021_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF021Ths035IsNotNull() {
            addCriterion("F021_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF021Ths035EqualTo(String value) {
            addCriterion("F021_THS035 =", value, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035NotEqualTo(String value) {
            addCriterion("F021_THS035 <>", value, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035GreaterThan(String value) {
            addCriterion("F021_THS035 >", value, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F021_THS035 >=", value, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035LessThan(String value) {
            addCriterion("F021_THS035 <", value, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035LessThanOrEqualTo(String value) {
            addCriterion("F021_THS035 <=", value, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035Like(String value) {
            addCriterion("F021_THS035 like", value, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035NotLike(String value) {
            addCriterion("F021_THS035 not like", value, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035In(List<String> values) {
            addCriterion("F021_THS035 in", values, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035NotIn(List<String> values) {
            addCriterion("F021_THS035 not in", values, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035Between(String value1, String value2) {
            addCriterion("F021_THS035 between", value1, value2, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF021Ths035NotBetween(String value1, String value2) {
            addCriterion("F021_THS035 not between", value1, value2, "f021Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035IsNull() {
            addCriterion("F022_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF022Ths035IsNotNull() {
            addCriterion("F022_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF022Ths035EqualTo(BigDecimal value) {
            addCriterion("F022_THS035 =", value, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035NotEqualTo(BigDecimal value) {
            addCriterion("F022_THS035 <>", value, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035GreaterThan(BigDecimal value) {
            addCriterion("F022_THS035 >", value, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F022_THS035 >=", value, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035LessThan(BigDecimal value) {
            addCriterion("F022_THS035 <", value, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035LessThanOrEqualTo(BigDecimal value) {
            addCriterion("F022_THS035 <=", value, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035In(List<BigDecimal> values) {
            addCriterion("F022_THS035 in", values, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035NotIn(List<BigDecimal> values) {
            addCriterion("F022_THS035 not in", values, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("F022_THS035 between", value1, value2, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF022Ths035NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F022_THS035 not between", value1, value2, "f022Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035IsNull() {
            addCriterion("F023_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF023Ths035IsNotNull() {
            addCriterion("F023_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF023Ths035EqualTo(BigDecimal value) {
            addCriterion("F023_THS035 =", value, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035NotEqualTo(BigDecimal value) {
            addCriterion("F023_THS035 <>", value, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035GreaterThan(BigDecimal value) {
            addCriterion("F023_THS035 >", value, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F023_THS035 >=", value, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035LessThan(BigDecimal value) {
            addCriterion("F023_THS035 <", value, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035LessThanOrEqualTo(BigDecimal value) {
            addCriterion("F023_THS035 <=", value, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035In(List<BigDecimal> values) {
            addCriterion("F023_THS035 in", values, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035NotIn(List<BigDecimal> values) {
            addCriterion("F023_THS035 not in", values, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("F023_THS035 between", value1, value2, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF023Ths035NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F023_THS035 not between", value1, value2, "f023Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035IsNull() {
            addCriterion("F024_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF024Ths035IsNotNull() {
            addCriterion("F024_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF024Ths035EqualTo(String value) {
            addCriterion("F024_THS035 =", value, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035NotEqualTo(String value) {
            addCriterion("F024_THS035 <>", value, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035GreaterThan(String value) {
            addCriterion("F024_THS035 >", value, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F024_THS035 >=", value, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035LessThan(String value) {
            addCriterion("F024_THS035 <", value, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035LessThanOrEqualTo(String value) {
            addCriterion("F024_THS035 <=", value, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035Like(String value) {
            addCriterion("F024_THS035 like", value, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035NotLike(String value) {
            addCriterion("F024_THS035 not like", value, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035In(List<String> values) {
            addCriterion("F024_THS035 in", values, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035NotIn(List<String> values) {
            addCriterion("F024_THS035 not in", values, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035Between(String value1, String value2) {
            addCriterion("F024_THS035 between", value1, value2, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF024Ths035NotBetween(String value1, String value2) {
            addCriterion("F024_THS035 not between", value1, value2, "f024Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035IsNull() {
            addCriterion("F025_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF025Ths035IsNotNull() {
            addCriterion("F025_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF025Ths035EqualTo(Date value) {
            addCriterion("F025_THS035 =", value, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035NotEqualTo(Date value) {
            addCriterion("F025_THS035 <>", value, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035GreaterThan(Date value) {
            addCriterion("F025_THS035 >", value, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035GreaterThanOrEqualTo(Date value) {
            addCriterion("F025_THS035 >=", value, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035LessThan(Date value) {
            addCriterion("F025_THS035 <", value, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035LessThanOrEqualTo(Date value) {
            addCriterion("F025_THS035 <=", value, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035In(List<Date> values) {
            addCriterion("F025_THS035 in", values, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035NotIn(List<Date> values) {
            addCriterion("F025_THS035 not in", values, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035Between(Date value1, Date value2) {
            addCriterion("F025_THS035 between", value1, value2, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF025Ths035NotBetween(Date value1, Date value2) {
            addCriterion("F025_THS035 not between", value1, value2, "f025Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035IsNull() {
            addCriterion("F026_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF026Ths035IsNotNull() {
            addCriterion("F026_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF026Ths035EqualTo(String value) {
            addCriterion("F026_THS035 =", value, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035NotEqualTo(String value) {
            addCriterion("F026_THS035 <>", value, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035GreaterThan(String value) {
            addCriterion("F026_THS035 >", value, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F026_THS035 >=", value, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035LessThan(String value) {
            addCriterion("F026_THS035 <", value, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035LessThanOrEqualTo(String value) {
            addCriterion("F026_THS035 <=", value, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035Like(String value) {
            addCriterion("F026_THS035 like", value, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035NotLike(String value) {
            addCriterion("F026_THS035 not like", value, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035In(List<String> values) {
            addCriterion("F026_THS035 in", values, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035NotIn(List<String> values) {
            addCriterion("F026_THS035 not in", values, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035Between(String value1, String value2) {
            addCriterion("F026_THS035 between", value1, value2, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF026Ths035NotBetween(String value1, String value2) {
            addCriterion("F026_THS035 not between", value1, value2, "f026Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035IsNull() {
            addCriterion("F027_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF027Ths035IsNotNull() {
            addCriterion("F027_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF027Ths035EqualTo(String value) {
            addCriterion("F027_THS035 =", value, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035NotEqualTo(String value) {
            addCriterion("F027_THS035 <>", value, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035GreaterThan(String value) {
            addCriterion("F027_THS035 >", value, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F027_THS035 >=", value, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035LessThan(String value) {
            addCriterion("F027_THS035 <", value, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035LessThanOrEqualTo(String value) {
            addCriterion("F027_THS035 <=", value, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035Like(String value) {
            addCriterion("F027_THS035 like", value, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035NotLike(String value) {
            addCriterion("F027_THS035 not like", value, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035In(List<String> values) {
            addCriterion("F027_THS035 in", values, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035NotIn(List<String> values) {
            addCriterion("F027_THS035 not in", values, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035Between(String value1, String value2) {
            addCriterion("F027_THS035 between", value1, value2, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF027Ths035NotBetween(String value1, String value2) {
            addCriterion("F027_THS035 not between", value1, value2, "f027Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035IsNull() {
            addCriterion("F028_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF028Ths035IsNotNull() {
            addCriterion("F028_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF028Ths035EqualTo(String value) {
            addCriterion("F028_THS035 =", value, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035NotEqualTo(String value) {
            addCriterion("F028_THS035 <>", value, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035GreaterThan(String value) {
            addCriterion("F028_THS035 >", value, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F028_THS035 >=", value, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035LessThan(String value) {
            addCriterion("F028_THS035 <", value, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035LessThanOrEqualTo(String value) {
            addCriterion("F028_THS035 <=", value, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035Like(String value) {
            addCriterion("F028_THS035 like", value, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035NotLike(String value) {
            addCriterion("F028_THS035 not like", value, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035In(List<String> values) {
            addCriterion("F028_THS035 in", values, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035NotIn(List<String> values) {
            addCriterion("F028_THS035 not in", values, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035Between(String value1, String value2) {
            addCriterion("F028_THS035 between", value1, value2, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF028Ths035NotBetween(String value1, String value2) {
            addCriterion("F028_THS035 not between", value1, value2, "f028Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035IsNull() {
            addCriterion("F029_THS035 is null");
            return (Criteria) this;
        }

        public Criteria andF029Ths035IsNotNull() {
            addCriterion("F029_THS035 is not null");
            return (Criteria) this;
        }

        public Criteria andF029Ths035EqualTo(String value) {
            addCriterion("F029_THS035 =", value, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035NotEqualTo(String value) {
            addCriterion("F029_THS035 <>", value, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035GreaterThan(String value) {
            addCriterion("F029_THS035 >", value, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035GreaterThanOrEqualTo(String value) {
            addCriterion("F029_THS035 >=", value, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035LessThan(String value) {
            addCriterion("F029_THS035 <", value, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035LessThanOrEqualTo(String value) {
            addCriterion("F029_THS035 <=", value, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035Like(String value) {
            addCriterion("F029_THS035 like", value, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035NotLike(String value) {
            addCriterion("F029_THS035 not like", value, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035In(List<String> values) {
            addCriterion("F029_THS035 in", values, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035NotIn(List<String> values) {
            addCriterion("F029_THS035 not in", values, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035Between(String value1, String value2) {
            addCriterion("F029_THS035 between", value1, value2, "f029Ths035");
            return (Criteria) this;
        }

        public Criteria andF029Ths035NotBetween(String value1, String value2) {
            addCriterion("F029_THS035 not between", value1, value2, "f029Ths035");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THS035
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 23 16:24:32 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THS035
     *
     * @mbggenerated Thu Jun 23 16:24:32 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}