package com.mrbt.mvc.model.funds;

import java.math.BigDecimal;
import java.util.Date;

public class Ths043 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.SEQ
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private BigDecimal seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.CTIME_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private Date ctimeThs043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.RTIME_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private Date rtimeThs043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.F001_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private String f001Ths043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.F002_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private Date f002Ths043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.F003_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private BigDecimal f003Ths043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.F004_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private BigDecimal f004Ths043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.F005_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private BigDecimal f005Ths043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.F006_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private BigDecimal f006Ths043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.F007_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private BigDecimal f007Ths043;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THS043.F008_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    private BigDecimal f008Ths043;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.SEQ
     *
     * @return the value of THS043.SEQ
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public BigDecimal getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.SEQ
     *
     * @param seq the value for THS043.SEQ
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setSeq(BigDecimal seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.CTIME_THS043
     *
     * @return the value of THS043.CTIME_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public Date getCtimeThs043() {
        return ctimeThs043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.CTIME_THS043
     *
     * @param ctimeThs043 the value for THS043.CTIME_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setCtimeThs043(Date ctimeThs043) {
        this.ctimeThs043 = ctimeThs043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.RTIME_THS043
     *
     * @return the value of THS043.RTIME_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public Date getRtimeThs043() {
        return rtimeThs043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.RTIME_THS043
     *
     * @param rtimeThs043 the value for THS043.RTIME_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setRtimeThs043(Date rtimeThs043) {
        this.rtimeThs043 = rtimeThs043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.F001_THS043
     *
     * @return the value of THS043.F001_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public String getF001Ths043() {
        return f001Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.F001_THS043
     *
     * @param f001Ths043 the value for THS043.F001_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setF001Ths043(String f001Ths043) {
        this.f001Ths043 = f001Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.F002_THS043
     *
     * @return the value of THS043.F002_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public Date getF002Ths043() {
        return f002Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.F002_THS043
     *
     * @param f002Ths043 the value for THS043.F002_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setF002Ths043(Date f002Ths043) {
        this.f002Ths043 = f002Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.F003_THS043
     *
     * @return the value of THS043.F003_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public BigDecimal getF003Ths043() {
        return f003Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.F003_THS043
     *
     * @param f003Ths043 the value for THS043.F003_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setF003Ths043(BigDecimal f003Ths043) {
        this.f003Ths043 = f003Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.F004_THS043
     *
     * @return the value of THS043.F004_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public BigDecimal getF004Ths043() {
        return f004Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.F004_THS043
     *
     * @param f004Ths043 the value for THS043.F004_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setF004Ths043(BigDecimal f004Ths043) {
        this.f004Ths043 = f004Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.F005_THS043
     *
     * @return the value of THS043.F005_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public BigDecimal getF005Ths043() {
        return f005Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.F005_THS043
     *
     * @param f005Ths043 the value for THS043.F005_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setF005Ths043(BigDecimal f005Ths043) {
        this.f005Ths043 = f005Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.F006_THS043
     *
     * @return the value of THS043.F006_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public BigDecimal getF006Ths043() {
        return f006Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.F006_THS043
     *
     * @param f006Ths043 the value for THS043.F006_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setF006Ths043(BigDecimal f006Ths043) {
        this.f006Ths043 = f006Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.F007_THS043
     *
     * @return the value of THS043.F007_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public BigDecimal getF007Ths043() {
        return f007Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.F007_THS043
     *
     * @param f007Ths043 the value for THS043.F007_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setF007Ths043(BigDecimal f007Ths043) {
        this.f007Ths043 = f007Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THS043.F008_THS043
     *
     * @return the value of THS043.F008_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public BigDecimal getF008Ths043() {
        return f008Ths043;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THS043.F008_THS043
     *
     * @param f008Ths043 the value for THS043.F008_THS043
     *
     * @mbggenerated Thu Jun 23 16:26:01 CST 2016
     */
    public void setF008Ths043(BigDecimal f008Ths043) {
        this.f008Ths043 = f008Ths043;
    }
}