package com.mrbt.mvc.model.funds;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Ths001Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public Ths001Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqIsNull() {
            addCriterion("SEQ is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(BigDecimal value) {
            addCriterion("SEQ =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(BigDecimal value) {
            addCriterion("SEQ <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(BigDecimal value) {
            addCriterion("SEQ >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SEQ >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(BigDecimal value) {
            addCriterion("SEQ <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SEQ <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<BigDecimal> values) {
            addCriterion("SEQ in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<BigDecimal> values) {
            addCriterion("SEQ not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEQ between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEQ not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001IsNull() {
            addCriterion("CTIME_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001IsNotNull() {
            addCriterion("CTIME_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001EqualTo(Date value) {
            addCriterion("CTIME_THS001 =", value, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001NotEqualTo(Date value) {
            addCriterion("CTIME_THS001 <>", value, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001GreaterThan(Date value) {
            addCriterion("CTIME_THS001 >", value, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001GreaterThanOrEqualTo(Date value) {
            addCriterion("CTIME_THS001 >=", value, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001LessThan(Date value) {
            addCriterion("CTIME_THS001 <", value, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001LessThanOrEqualTo(Date value) {
            addCriterion("CTIME_THS001 <=", value, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001In(List<Date> values) {
            addCriterion("CTIME_THS001 in", values, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001NotIn(List<Date> values) {
            addCriterion("CTIME_THS001 not in", values, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001Between(Date value1, Date value2) {
            addCriterion("CTIME_THS001 between", value1, value2, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andCtimeThs001NotBetween(Date value1, Date value2) {
            addCriterion("CTIME_THS001 not between", value1, value2, "ctimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001IsNull() {
            addCriterion("RTIME_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001IsNotNull() {
            addCriterion("RTIME_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001EqualTo(Date value) {
            addCriterion("RTIME_THS001 =", value, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001NotEqualTo(Date value) {
            addCriterion("RTIME_THS001 <>", value, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001GreaterThan(Date value) {
            addCriterion("RTIME_THS001 >", value, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001GreaterThanOrEqualTo(Date value) {
            addCriterion("RTIME_THS001 >=", value, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001LessThan(Date value) {
            addCriterion("RTIME_THS001 <", value, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001LessThanOrEqualTo(Date value) {
            addCriterion("RTIME_THS001 <=", value, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001In(List<Date> values) {
            addCriterion("RTIME_THS001 in", values, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001NotIn(List<Date> values) {
            addCriterion("RTIME_THS001 not in", values, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001Between(Date value1, Date value2) {
            addCriterion("RTIME_THS001 between", value1, value2, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andRtimeThs001NotBetween(Date value1, Date value2) {
            addCriterion("RTIME_THS001 not between", value1, value2, "rtimeThs001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001IsNull() {
            addCriterion("F001_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF001Ths001IsNotNull() {
            addCriterion("F001_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF001Ths001EqualTo(String value) {
            addCriterion("F001_THS001 =", value, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001NotEqualTo(String value) {
            addCriterion("F001_THS001 <>", value, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001GreaterThan(String value) {
            addCriterion("F001_THS001 >", value, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F001_THS001 >=", value, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001LessThan(String value) {
            addCriterion("F001_THS001 <", value, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001LessThanOrEqualTo(String value) {
            addCriterion("F001_THS001 <=", value, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001Like(String value) {
            addCriterion("F001_THS001 like", value, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001NotLike(String value) {
            addCriterion("F001_THS001 not like", value, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001In(List<String> values) {
            addCriterion("F001_THS001 in", values, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001NotIn(List<String> values) {
            addCriterion("F001_THS001 not in", values, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001Between(String value1, String value2) {
            addCriterion("F001_THS001 between", value1, value2, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF001Ths001NotBetween(String value1, String value2) {
            addCriterion("F001_THS001 not between", value1, value2, "f001Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001IsNull() {
            addCriterion("F002_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF002Ths001IsNotNull() {
            addCriterion("F002_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF002Ths001EqualTo(String value) {
            addCriterion("F002_THS001 =", value, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001NotEqualTo(String value) {
            addCriterion("F002_THS001 <>", value, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001GreaterThan(String value) {
            addCriterion("F002_THS001 >", value, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F002_THS001 >=", value, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001LessThan(String value) {
            addCriterion("F002_THS001 <", value, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001LessThanOrEqualTo(String value) {
            addCriterion("F002_THS001 <=", value, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001Like(String value) {
            addCriterion("F002_THS001 like", value, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001NotLike(String value) {
            addCriterion("F002_THS001 not like", value, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001In(List<String> values) {
            addCriterion("F002_THS001 in", values, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001NotIn(List<String> values) {
            addCriterion("F002_THS001 not in", values, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001Between(String value1, String value2) {
            addCriterion("F002_THS001 between", value1, value2, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF002Ths001NotBetween(String value1, String value2) {
            addCriterion("F002_THS001 not between", value1, value2, "f002Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001IsNull() {
            addCriterion("F003_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF003Ths001IsNotNull() {
            addCriterion("F003_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF003Ths001EqualTo(String value) {
            addCriterion("F003_THS001 =", value, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001NotEqualTo(String value) {
            addCriterion("F003_THS001 <>", value, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001GreaterThan(String value) {
            addCriterion("F003_THS001 >", value, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F003_THS001 >=", value, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001LessThan(String value) {
            addCriterion("F003_THS001 <", value, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001LessThanOrEqualTo(String value) {
            addCriterion("F003_THS001 <=", value, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001Like(String value) {
            addCriterion("F003_THS001 like", value, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001NotLike(String value) {
            addCriterion("F003_THS001 not like", value, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001In(List<String> values) {
            addCriterion("F003_THS001 in", values, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001NotIn(List<String> values) {
            addCriterion("F003_THS001 not in", values, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001Between(String value1, String value2) {
            addCriterion("F003_THS001 between", value1, value2, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF003Ths001NotBetween(String value1, String value2) {
            addCriterion("F003_THS001 not between", value1, value2, "f003Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001IsNull() {
            addCriterion("F004_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF004Ths001IsNotNull() {
            addCriterion("F004_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF004Ths001EqualTo(String value) {
            addCriterion("F004_THS001 =", value, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001NotEqualTo(String value) {
            addCriterion("F004_THS001 <>", value, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001GreaterThan(String value) {
            addCriterion("F004_THS001 >", value, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F004_THS001 >=", value, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001LessThan(String value) {
            addCriterion("F004_THS001 <", value, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001LessThanOrEqualTo(String value) {
            addCriterion("F004_THS001 <=", value, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001Like(String value) {
            addCriterion("F004_THS001 like", value, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001NotLike(String value) {
            addCriterion("F004_THS001 not like", value, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001In(List<String> values) {
            addCriterion("F004_THS001 in", values, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001NotIn(List<String> values) {
            addCriterion("F004_THS001 not in", values, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001Between(String value1, String value2) {
            addCriterion("F004_THS001 between", value1, value2, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF004Ths001NotBetween(String value1, String value2) {
            addCriterion("F004_THS001 not between", value1, value2, "f004Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001IsNull() {
            addCriterion("F005_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF005Ths001IsNotNull() {
            addCriterion("F005_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF005Ths001EqualTo(String value) {
            addCriterion("F005_THS001 =", value, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001NotEqualTo(String value) {
            addCriterion("F005_THS001 <>", value, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001GreaterThan(String value) {
            addCriterion("F005_THS001 >", value, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F005_THS001 >=", value, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001LessThan(String value) {
            addCriterion("F005_THS001 <", value, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001LessThanOrEqualTo(String value) {
            addCriterion("F005_THS001 <=", value, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001Like(String value) {
            addCriterion("F005_THS001 like", value, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001NotLike(String value) {
            addCriterion("F005_THS001 not like", value, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001In(List<String> values) {
            addCriterion("F005_THS001 in", values, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001NotIn(List<String> values) {
            addCriterion("F005_THS001 not in", values, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001Between(String value1, String value2) {
            addCriterion("F005_THS001 between", value1, value2, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF005Ths001NotBetween(String value1, String value2) {
            addCriterion("F005_THS001 not between", value1, value2, "f005Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001IsNull() {
            addCriterion("F006_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF006Ths001IsNotNull() {
            addCriterion("F006_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF006Ths001EqualTo(String value) {
            addCriterion("F006_THS001 =", value, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001NotEqualTo(String value) {
            addCriterion("F006_THS001 <>", value, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001GreaterThan(String value) {
            addCriterion("F006_THS001 >", value, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F006_THS001 >=", value, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001LessThan(String value) {
            addCriterion("F006_THS001 <", value, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001LessThanOrEqualTo(String value) {
            addCriterion("F006_THS001 <=", value, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001Like(String value) {
            addCriterion("F006_THS001 like", value, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001NotLike(String value) {
            addCriterion("F006_THS001 not like", value, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001In(List<String> values) {
            addCriterion("F006_THS001 in", values, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001NotIn(List<String> values) {
            addCriterion("F006_THS001 not in", values, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001Between(String value1, String value2) {
            addCriterion("F006_THS001 between", value1, value2, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF006Ths001NotBetween(String value1, String value2) {
            addCriterion("F006_THS001 not between", value1, value2, "f006Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001IsNull() {
            addCriterion("F007_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF007Ths001IsNotNull() {
            addCriterion("F007_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF007Ths001EqualTo(String value) {
            addCriterion("F007_THS001 =", value, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001NotEqualTo(String value) {
            addCriterion("F007_THS001 <>", value, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001GreaterThan(String value) {
            addCriterion("F007_THS001 >", value, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F007_THS001 >=", value, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001LessThan(String value) {
            addCriterion("F007_THS001 <", value, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001LessThanOrEqualTo(String value) {
            addCriterion("F007_THS001 <=", value, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001Like(String value) {
            addCriterion("F007_THS001 like", value, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001NotLike(String value) {
            addCriterion("F007_THS001 not like", value, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001In(List<String> values) {
            addCriterion("F007_THS001 in", values, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001NotIn(List<String> values) {
            addCriterion("F007_THS001 not in", values, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001Between(String value1, String value2) {
            addCriterion("F007_THS001 between", value1, value2, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF007Ths001NotBetween(String value1, String value2) {
            addCriterion("F007_THS001 not between", value1, value2, "f007Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001IsNull() {
            addCriterion("F008_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF008Ths001IsNotNull() {
            addCriterion("F008_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF008Ths001EqualTo(String value) {
            addCriterion("F008_THS001 =", value, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001NotEqualTo(String value) {
            addCriterion("F008_THS001 <>", value, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001GreaterThan(String value) {
            addCriterion("F008_THS001 >", value, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F008_THS001 >=", value, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001LessThan(String value) {
            addCriterion("F008_THS001 <", value, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001LessThanOrEqualTo(String value) {
            addCriterion("F008_THS001 <=", value, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001Like(String value) {
            addCriterion("F008_THS001 like", value, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001NotLike(String value) {
            addCriterion("F008_THS001 not like", value, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001In(List<String> values) {
            addCriterion("F008_THS001 in", values, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001NotIn(List<String> values) {
            addCriterion("F008_THS001 not in", values, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001Between(String value1, String value2) {
            addCriterion("F008_THS001 between", value1, value2, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF008Ths001NotBetween(String value1, String value2) {
            addCriterion("F008_THS001 not between", value1, value2, "f008Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001IsNull() {
            addCriterion("F009_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF009Ths001IsNotNull() {
            addCriterion("F009_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF009Ths001EqualTo(String value) {
            addCriterion("F009_THS001 =", value, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001NotEqualTo(String value) {
            addCriterion("F009_THS001 <>", value, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001GreaterThan(String value) {
            addCriterion("F009_THS001 >", value, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F009_THS001 >=", value, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001LessThan(String value) {
            addCriterion("F009_THS001 <", value, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001LessThanOrEqualTo(String value) {
            addCriterion("F009_THS001 <=", value, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001Like(String value) {
            addCriterion("F009_THS001 like", value, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001NotLike(String value) {
            addCriterion("F009_THS001 not like", value, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001In(List<String> values) {
            addCriterion("F009_THS001 in", values, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001NotIn(List<String> values) {
            addCriterion("F009_THS001 not in", values, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001Between(String value1, String value2) {
            addCriterion("F009_THS001 between", value1, value2, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF009Ths001NotBetween(String value1, String value2) {
            addCriterion("F009_THS001 not between", value1, value2, "f009Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001IsNull() {
            addCriterion("F010_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF010Ths001IsNotNull() {
            addCriterion("F010_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF010Ths001EqualTo(Date value) {
            addCriterion("F010_THS001 =", value, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001NotEqualTo(Date value) {
            addCriterion("F010_THS001 <>", value, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001GreaterThan(Date value) {
            addCriterion("F010_THS001 >", value, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001GreaterThanOrEqualTo(Date value) {
            addCriterion("F010_THS001 >=", value, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001LessThan(Date value) {
            addCriterion("F010_THS001 <", value, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001LessThanOrEqualTo(Date value) {
            addCriterion("F010_THS001 <=", value, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001In(List<Date> values) {
            addCriterion("F010_THS001 in", values, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001NotIn(List<Date> values) {
            addCriterion("F010_THS001 not in", values, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001Between(Date value1, Date value2) {
            addCriterion("F010_THS001 between", value1, value2, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF010Ths001NotBetween(Date value1, Date value2) {
            addCriterion("F010_THS001 not between", value1, value2, "f010Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001IsNull() {
            addCriterion("F011_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF011Ths001IsNotNull() {
            addCriterion("F011_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF011Ths001EqualTo(Date value) {
            addCriterion("F011_THS001 =", value, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001NotEqualTo(Date value) {
            addCriterion("F011_THS001 <>", value, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001GreaterThan(Date value) {
            addCriterion("F011_THS001 >", value, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001GreaterThanOrEqualTo(Date value) {
            addCriterion("F011_THS001 >=", value, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001LessThan(Date value) {
            addCriterion("F011_THS001 <", value, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001LessThanOrEqualTo(Date value) {
            addCriterion("F011_THS001 <=", value, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001In(List<Date> values) {
            addCriterion("F011_THS001 in", values, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001NotIn(List<Date> values) {
            addCriterion("F011_THS001 not in", values, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001Between(Date value1, Date value2) {
            addCriterion("F011_THS001 between", value1, value2, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF011Ths001NotBetween(Date value1, Date value2) {
            addCriterion("F011_THS001 not between", value1, value2, "f011Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001IsNull() {
            addCriterion("F012_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF012Ths001IsNotNull() {
            addCriterion("F012_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF012Ths001EqualTo(String value) {
            addCriterion("F012_THS001 =", value, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001NotEqualTo(String value) {
            addCriterion("F012_THS001 <>", value, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001GreaterThan(String value) {
            addCriterion("F012_THS001 >", value, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F012_THS001 >=", value, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001LessThan(String value) {
            addCriterion("F012_THS001 <", value, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001LessThanOrEqualTo(String value) {
            addCriterion("F012_THS001 <=", value, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001Like(String value) {
            addCriterion("F012_THS001 like", value, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001NotLike(String value) {
            addCriterion("F012_THS001 not like", value, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001In(List<String> values) {
            addCriterion("F012_THS001 in", values, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001NotIn(List<String> values) {
            addCriterion("F012_THS001 not in", values, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001Between(String value1, String value2) {
            addCriterion("F012_THS001 between", value1, value2, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF012Ths001NotBetween(String value1, String value2) {
            addCriterion("F012_THS001 not between", value1, value2, "f012Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001IsNull() {
            addCriterion("F013_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF013Ths001IsNotNull() {
            addCriterion("F013_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF013Ths001EqualTo(String value) {
            addCriterion("F013_THS001 =", value, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001NotEqualTo(String value) {
            addCriterion("F013_THS001 <>", value, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001GreaterThan(String value) {
            addCriterion("F013_THS001 >", value, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F013_THS001 >=", value, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001LessThan(String value) {
            addCriterion("F013_THS001 <", value, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001LessThanOrEqualTo(String value) {
            addCriterion("F013_THS001 <=", value, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001Like(String value) {
            addCriterion("F013_THS001 like", value, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001NotLike(String value) {
            addCriterion("F013_THS001 not like", value, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001In(List<String> values) {
            addCriterion("F013_THS001 in", values, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001NotIn(List<String> values) {
            addCriterion("F013_THS001 not in", values, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001Between(String value1, String value2) {
            addCriterion("F013_THS001 between", value1, value2, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF013Ths001NotBetween(String value1, String value2) {
            addCriterion("F013_THS001 not between", value1, value2, "f013Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001IsNull() {
            addCriterion("F014_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF014Ths001IsNotNull() {
            addCriterion("F014_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF014Ths001EqualTo(String value) {
            addCriterion("F014_THS001 =", value, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001NotEqualTo(String value) {
            addCriterion("F014_THS001 <>", value, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001GreaterThan(String value) {
            addCriterion("F014_THS001 >", value, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F014_THS001 >=", value, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001LessThan(String value) {
            addCriterion("F014_THS001 <", value, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001LessThanOrEqualTo(String value) {
            addCriterion("F014_THS001 <=", value, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001Like(String value) {
            addCriterion("F014_THS001 like", value, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001NotLike(String value) {
            addCriterion("F014_THS001 not like", value, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001In(List<String> values) {
            addCriterion("F014_THS001 in", values, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001NotIn(List<String> values) {
            addCriterion("F014_THS001 not in", values, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001Between(String value1, String value2) {
            addCriterion("F014_THS001 between", value1, value2, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF014Ths001NotBetween(String value1, String value2) {
            addCriterion("F014_THS001 not between", value1, value2, "f014Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001IsNull() {
            addCriterion("F015_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF015Ths001IsNotNull() {
            addCriterion("F015_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF015Ths001EqualTo(String value) {
            addCriterion("F015_THS001 =", value, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001NotEqualTo(String value) {
            addCriterion("F015_THS001 <>", value, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001GreaterThan(String value) {
            addCriterion("F015_THS001 >", value, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F015_THS001 >=", value, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001LessThan(String value) {
            addCriterion("F015_THS001 <", value, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001LessThanOrEqualTo(String value) {
            addCriterion("F015_THS001 <=", value, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001Like(String value) {
            addCriterion("F015_THS001 like", value, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001NotLike(String value) {
            addCriterion("F015_THS001 not like", value, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001In(List<String> values) {
            addCriterion("F015_THS001 in", values, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001NotIn(List<String> values) {
            addCriterion("F015_THS001 not in", values, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001Between(String value1, String value2) {
            addCriterion("F015_THS001 between", value1, value2, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF015Ths001NotBetween(String value1, String value2) {
            addCriterion("F015_THS001 not between", value1, value2, "f015Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001IsNull() {
            addCriterion("F016_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF016Ths001IsNotNull() {
            addCriterion("F016_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF016Ths001EqualTo(String value) {
            addCriterion("F016_THS001 =", value, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001NotEqualTo(String value) {
            addCriterion("F016_THS001 <>", value, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001GreaterThan(String value) {
            addCriterion("F016_THS001 >", value, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F016_THS001 >=", value, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001LessThan(String value) {
            addCriterion("F016_THS001 <", value, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001LessThanOrEqualTo(String value) {
            addCriterion("F016_THS001 <=", value, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001Like(String value) {
            addCriterion("F016_THS001 like", value, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001NotLike(String value) {
            addCriterion("F016_THS001 not like", value, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001In(List<String> values) {
            addCriterion("F016_THS001 in", values, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001NotIn(List<String> values) {
            addCriterion("F016_THS001 not in", values, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001Between(String value1, String value2) {
            addCriterion("F016_THS001 between", value1, value2, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF016Ths001NotBetween(String value1, String value2) {
            addCriterion("F016_THS001 not between", value1, value2, "f016Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001IsNull() {
            addCriterion("F017_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF017Ths001IsNotNull() {
            addCriterion("F017_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF017Ths001EqualTo(Short value) {
            addCriterion("F017_THS001 =", value, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001NotEqualTo(Short value) {
            addCriterion("F017_THS001 <>", value, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001GreaterThan(Short value) {
            addCriterion("F017_THS001 >", value, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001GreaterThanOrEqualTo(Short value) {
            addCriterion("F017_THS001 >=", value, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001LessThan(Short value) {
            addCriterion("F017_THS001 <", value, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001LessThanOrEqualTo(Short value) {
            addCriterion("F017_THS001 <=", value, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001In(List<Short> values) {
            addCriterion("F017_THS001 in", values, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001NotIn(List<Short> values) {
            addCriterion("F017_THS001 not in", values, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001Between(Short value1, Short value2) {
            addCriterion("F017_THS001 between", value1, value2, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF017Ths001NotBetween(Short value1, Short value2) {
            addCriterion("F017_THS001 not between", value1, value2, "f017Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001IsNull() {
            addCriterion("F018_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF018Ths001IsNotNull() {
            addCriterion("F018_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF018Ths001EqualTo(Short value) {
            addCriterion("F018_THS001 =", value, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001NotEqualTo(Short value) {
            addCriterion("F018_THS001 <>", value, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001GreaterThan(Short value) {
            addCriterion("F018_THS001 >", value, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001GreaterThanOrEqualTo(Short value) {
            addCriterion("F018_THS001 >=", value, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001LessThan(Short value) {
            addCriterion("F018_THS001 <", value, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001LessThanOrEqualTo(Short value) {
            addCriterion("F018_THS001 <=", value, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001In(List<Short> values) {
            addCriterion("F018_THS001 in", values, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001NotIn(List<Short> values) {
            addCriterion("F018_THS001 not in", values, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001Between(Short value1, Short value2) {
            addCriterion("F018_THS001 between", value1, value2, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF018Ths001NotBetween(Short value1, Short value2) {
            addCriterion("F018_THS001 not between", value1, value2, "f018Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001IsNull() {
            addCriterion("F019_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF019Ths001IsNotNull() {
            addCriterion("F019_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF019Ths001EqualTo(String value) {
            addCriterion("F019_THS001 =", value, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001NotEqualTo(String value) {
            addCriterion("F019_THS001 <>", value, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001GreaterThan(String value) {
            addCriterion("F019_THS001 >", value, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F019_THS001 >=", value, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001LessThan(String value) {
            addCriterion("F019_THS001 <", value, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001LessThanOrEqualTo(String value) {
            addCriterion("F019_THS001 <=", value, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001Like(String value) {
            addCriterion("F019_THS001 like", value, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001NotLike(String value) {
            addCriterion("F019_THS001 not like", value, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001In(List<String> values) {
            addCriterion("F019_THS001 in", values, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001NotIn(List<String> values) {
            addCriterion("F019_THS001 not in", values, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001Between(String value1, String value2) {
            addCriterion("F019_THS001 between", value1, value2, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF019Ths001NotBetween(String value1, String value2) {
            addCriterion("F019_THS001 not between", value1, value2, "f019Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001IsNull() {
            addCriterion("F020_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF020Ths001IsNotNull() {
            addCriterion("F020_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF020Ths001EqualTo(String value) {
            addCriterion("F020_THS001 =", value, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001NotEqualTo(String value) {
            addCriterion("F020_THS001 <>", value, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001GreaterThan(String value) {
            addCriterion("F020_THS001 >", value, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F020_THS001 >=", value, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001LessThan(String value) {
            addCriterion("F020_THS001 <", value, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001LessThanOrEqualTo(String value) {
            addCriterion("F020_THS001 <=", value, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001Like(String value) {
            addCriterion("F020_THS001 like", value, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001NotLike(String value) {
            addCriterion("F020_THS001 not like", value, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001In(List<String> values) {
            addCriterion("F020_THS001 in", values, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001NotIn(List<String> values) {
            addCriterion("F020_THS001 not in", values, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001Between(String value1, String value2) {
            addCriterion("F020_THS001 between", value1, value2, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF020Ths001NotBetween(String value1, String value2) {
            addCriterion("F020_THS001 not between", value1, value2, "f020Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001IsNull() {
            addCriterion("F021_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF021Ths001IsNotNull() {
            addCriterion("F021_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF021Ths001EqualTo(String value) {
            addCriterion("F021_THS001 =", value, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001NotEqualTo(String value) {
            addCriterion("F021_THS001 <>", value, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001GreaterThan(String value) {
            addCriterion("F021_THS001 >", value, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F021_THS001 >=", value, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001LessThan(String value) {
            addCriterion("F021_THS001 <", value, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001LessThanOrEqualTo(String value) {
            addCriterion("F021_THS001 <=", value, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001Like(String value) {
            addCriterion("F021_THS001 like", value, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001NotLike(String value) {
            addCriterion("F021_THS001 not like", value, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001In(List<String> values) {
            addCriterion("F021_THS001 in", values, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001NotIn(List<String> values) {
            addCriterion("F021_THS001 not in", values, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001Between(String value1, String value2) {
            addCriterion("F021_THS001 between", value1, value2, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF021Ths001NotBetween(String value1, String value2) {
            addCriterion("F021_THS001 not between", value1, value2, "f021Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001IsNull() {
            addCriterion("F022_THS001 is null");
            return (Criteria) this;
        }

        public Criteria andF022Ths001IsNotNull() {
            addCriterion("F022_THS001 is not null");
            return (Criteria) this;
        }

        public Criteria andF022Ths001EqualTo(String value) {
            addCriterion("F022_THS001 =", value, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001NotEqualTo(String value) {
            addCriterion("F022_THS001 <>", value, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001GreaterThan(String value) {
            addCriterion("F022_THS001 >", value, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001GreaterThanOrEqualTo(String value) {
            addCriterion("F022_THS001 >=", value, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001LessThan(String value) {
            addCriterion("F022_THS001 <", value, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001LessThanOrEqualTo(String value) {
            addCriterion("F022_THS001 <=", value, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001Like(String value) {
            addCriterion("F022_THS001 like", value, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001NotLike(String value) {
            addCriterion("F022_THS001 not like", value, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001In(List<String> values) {
            addCriterion("F022_THS001 in", values, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001NotIn(List<String> values) {
            addCriterion("F022_THS001 not in", values, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001Between(String value1, String value2) {
            addCriterion("F022_THS001 between", value1, value2, "f022Ths001");
            return (Criteria) this;
        }

        public Criteria andF022Ths001NotBetween(String value1, String value2) {
            addCriterion("F022_THS001 not between", value1, value2, "f022Ths001");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THS001
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 23 16:23:11 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THS001
     *
     * @mbggenerated Thu Jun 23 16:23:11 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}