package com.mrbt.mvc.model.funds;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Ths001 {
	//基金基础
	private Ths035 ths035;
	//净值
	private List<Ths043> ths043s;
	public List<Ths043> getThs043s() {
		return ths043s;
	}

	public void setThs043s(List<Ths043> ths043s) {
		this.ths043s = ths043s;
	}

	public Ths035 getThs035() {
		return ths035;
	}

	public void setThs035(Ths035 ths035) {
		this.ths035 = ths035;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.SEQ
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private BigDecimal seq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.CTIME_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private Date ctimeThs001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.RTIME_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private Date rtimeThs001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F001_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f001Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F002_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f002Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F003_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f003Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F004_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f004Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F005_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f005Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F006_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f006Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F007_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f007Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F008_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f008Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F009_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f009Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F010_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private Date f010Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F011_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private Date f011Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F012_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f012Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F013_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f013Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F014_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f014Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F015_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f015Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F016_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f016Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F017_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private Short f017Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F018_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private Short f018Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F019_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f019Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F020_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f020Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F021_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f021Ths001;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS001.F022_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	private String f022Ths001;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.SEQ
	 *
	 * @return the value of THS001.SEQ
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public BigDecimal getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.SEQ
	 *
	 * @param seq
	 *            the value for THS001.SEQ
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setSeq(BigDecimal seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.CTIME_THS001
	 *
	 * @return the value of THS001.CTIME_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public Date getCtimeThs001() {
		return ctimeThs001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.CTIME_THS001
	 *
	 * @param ctimeThs001
	 *            the value for THS001.CTIME_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setCtimeThs001(Date ctimeThs001) {
		this.ctimeThs001 = ctimeThs001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.RTIME_THS001
	 *
	 * @return the value of THS001.RTIME_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public Date getRtimeThs001() {
		return rtimeThs001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.RTIME_THS001
	 *
	 * @param rtimeThs001
	 *            the value for THS001.RTIME_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setRtimeThs001(Date rtimeThs001) {
		this.rtimeThs001 = rtimeThs001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F001_THS001
	 *
	 * @return the value of THS001.F001_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF001Ths001() {
		return f001Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F001_THS001
	 *
	 * @param f001Ths001
	 *            the value for THS001.F001_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF001Ths001(String f001Ths001) {
		this.f001Ths001 = f001Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F002_THS001
	 *
	 * @return the value of THS001.F002_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF002Ths001() {
		return f002Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F002_THS001
	 *
	 * @param f002Ths001
	 *            the value for THS001.F002_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF002Ths001(String f002Ths001) {
		this.f002Ths001 = f002Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F003_THS001
	 *
	 * @return the value of THS001.F003_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF003Ths001() {
		return f003Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F003_THS001
	 *
	 * @param f003Ths001
	 *            the value for THS001.F003_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF003Ths001(String f003Ths001) {
		this.f003Ths001 = f003Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F004_THS001
	 *
	 * @return the value of THS001.F004_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF004Ths001() {
		return f004Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F004_THS001
	 *
	 * @param f004Ths001
	 *            the value for THS001.F004_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF004Ths001(String f004Ths001) {
		this.f004Ths001 = f004Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F005_THS001
	 *
	 * @return the value of THS001.F005_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF005Ths001() {
		return f005Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F005_THS001
	 *
	 * @param f005Ths001
	 *            the value for THS001.F005_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF005Ths001(String f005Ths001) {
		this.f005Ths001 = f005Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F006_THS001
	 *
	 * @return the value of THS001.F006_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF006Ths001() {
		return f006Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F006_THS001
	 *
	 * @param f006Ths001
	 *            the value for THS001.F006_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF006Ths001(String f006Ths001) {
		this.f006Ths001 = f006Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F007_THS001
	 *
	 * @return the value of THS001.F007_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF007Ths001() {
		return f007Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F007_THS001
	 *
	 * @param f007Ths001
	 *            the value for THS001.F007_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF007Ths001(String f007Ths001) {
		this.f007Ths001 = f007Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F008_THS001
	 *
	 * @return the value of THS001.F008_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF008Ths001() {
		return f008Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F008_THS001
	 *
	 * @param f008Ths001
	 *            the value for THS001.F008_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF008Ths001(String f008Ths001) {
		this.f008Ths001 = f008Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F009_THS001
	 *
	 * @return the value of THS001.F009_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF009Ths001() {
		return f009Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F009_THS001
	 *
	 * @param f009Ths001
	 *            the value for THS001.F009_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF009Ths001(String f009Ths001) {
		this.f009Ths001 = f009Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F010_THS001
	 *
	 * @return the value of THS001.F010_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public Date getF010Ths001() {
		return f010Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F010_THS001
	 *
	 * @param f010Ths001
	 *            the value for THS001.F010_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF010Ths001(Date f010Ths001) {
		this.f010Ths001 = f010Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F011_THS001
	 *
	 * @return the value of THS001.F011_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public Date getF011Ths001() {
		return f011Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F011_THS001
	 *
	 * @param f011Ths001
	 *            the value for THS001.F011_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF011Ths001(Date f011Ths001) {
		this.f011Ths001 = f011Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F012_THS001
	 *
	 * @return the value of THS001.F012_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF012Ths001() {
		return f012Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F012_THS001
	 *
	 * @param f012Ths001
	 *            the value for THS001.F012_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF012Ths001(String f012Ths001) {
		this.f012Ths001 = f012Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F013_THS001
	 *
	 * @return the value of THS001.F013_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF013Ths001() {
		return f013Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F013_THS001
	 *
	 * @param f013Ths001
	 *            the value for THS001.F013_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF013Ths001(String f013Ths001) {
		this.f013Ths001 = f013Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F014_THS001
	 *
	 * @return the value of THS001.F014_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF014Ths001() {
		return f014Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F014_THS001
	 *
	 * @param f014Ths001
	 *            the value for THS001.F014_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF014Ths001(String f014Ths001) {
		this.f014Ths001 = f014Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F015_THS001
	 *
	 * @return the value of THS001.F015_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF015Ths001() {
		return f015Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F015_THS001
	 *
	 * @param f015Ths001
	 *            the value for THS001.F015_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF015Ths001(String f015Ths001) {
		this.f015Ths001 = f015Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F016_THS001
	 *
	 * @return the value of THS001.F016_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF016Ths001() {
		return f016Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F016_THS001
	 *
	 * @param f016Ths001
	 *            the value for THS001.F016_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF016Ths001(String f016Ths001) {
		this.f016Ths001 = f016Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F017_THS001
	 *
	 * @return the value of THS001.F017_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public Short getF017Ths001() {
		return f017Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F017_THS001
	 *
	 * @param f017Ths001
	 *            the value for THS001.F017_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF017Ths001(Short f017Ths001) {
		this.f017Ths001 = f017Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F018_THS001
	 *
	 * @return the value of THS001.F018_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public Short getF018Ths001() {
		return f018Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F018_THS001
	 *
	 * @param f018Ths001
	 *            the value for THS001.F018_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF018Ths001(Short f018Ths001) {
		this.f018Ths001 = f018Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F019_THS001
	 *
	 * @return the value of THS001.F019_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF019Ths001() {
		return f019Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F019_THS001
	 *
	 * @param f019Ths001
	 *            the value for THS001.F019_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF019Ths001(String f019Ths001) {
		this.f019Ths001 = f019Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F020_THS001
	 *
	 * @return the value of THS001.F020_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF020Ths001() {
		return f020Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F020_THS001
	 *
	 * @param f020Ths001
	 *            the value for THS001.F020_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF020Ths001(String f020Ths001) {
		this.f020Ths001 = f020Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F021_THS001
	 *
	 * @return the value of THS001.F021_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF021Ths001() {
		return f021Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F021_THS001
	 *
	 * @param f021Ths001
	 *            the value for THS001.F021_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF021Ths001(String f021Ths001) {
		this.f021Ths001 = f021Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS001.F022_THS001
	 *
	 * @return the value of THS001.F022_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public String getF022Ths001() {
		return f022Ths001;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS001.F022_THS001
	 *
	 * @param f022Ths001
	 *            the value for THS001.F022_THS001
	 *
	 * @mbggenerated Thu Jun 23 16:23:11 CST 2016
	 */
	public void setF022Ths001(String f022Ths001) {
		this.f022Ths001 = f022Ths001;
	}

	@Override
	public String toString() {
		StringBuffer stringBuffer = new StringBuffer();
		stringBuffer
				.append("Ths001 [seq=" + seq + ", ctimeThs001=" + ctimeThs001)
				.append(", rtimeThs001=" + rtimeThs001 + ", f001Ths001="
						+ f001Ths001)
				.append(", f002Ths001=" + f002Ths001 + ", f003Ths001="
						+ f003Ths001)
				.append(", f004Ths001=" + f004Ths001 + ", f005Ths001="
						+ f005Ths001)
				.append(", f006Ths001=" + f006Ths001 + ", f007Ths001="
						+ f007Ths001)
				.append(", f008Ths001=" + f008Ths001 + ", f009Ths001="
						+ f009Ths001)
				.append(", f010Ths001=" + f010Ths001 + ", f011Ths001="
						+ f011Ths001)
				.append(", f012Ths001=" + f012Ths001 + ", f013Ths001="
						+ f013Ths001)
				.append(", f014Ths001=" + f014Ths001 + ", f015Ths001="
						+ f015Ths001)
				.append(", f016Ths001=" + f016Ths001 + ", f017Ths001="
						+ f017Ths001)
				.append(", f018Ths001=" + f018Ths001 + ", f019Ths001="
						+ f019Ths001)
				.append(", f020Ths001=" + f020Ths001 + ", f021Ths001="
						+ f021Ths001)
				.append(", f022Ths001=" + f022Ths001).
				append(", ths035 =" + ths035 + "]");
		return stringBuffer.toString();
	}
}