package com.mrbt.oa.mvc.mapper;

import java.math.BigDecimal;

import org.apache.ibatis.annotations.Param;

import com.mrbt.oa.mvc.vo.BaseVo;
import com.mrbt.oa.mvc.vo.funds.FundsPackageRatio;
import com.mrbt.oa.mvc.vo.funds.FundsPackageRatioExample;

public interface BaseMapper {

	public int countByExample(Object example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin_menu
	 * 
	 * @mbggenerated Mon May 18 15:08:07 CST 2015
	 */
	public int deleteByPrimaryKey(Integer id);

	public int deleteByPrimaryKey(BigDecimal id);

	public int deleteByPrimaryKey(String id);

	public int deleteByExample(Object example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin_menu
	 * 
	 * @mbggenerated Mon May 18 15:08:07 CST 2015
	 */
	public int insert(BaseVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin_menu
	 * 
	 * @mbggenerated Mon May 18 15:08:07 CST 2015
	 */
	public int insertSelective(BaseVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin_menu
	 * 
	 * @mbggenerated Mon May 18 15:08:07 CST 2015
	 */
	public <D extends BaseVo> D selectByPrimaryKey(Integer id);

	public <D extends BaseVo> D selectByPrimaryKey(BigDecimal id);

	public <D extends BaseVo> D selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin_menu
	 * 
	 * @mbggenerated Mon May 18 15:08:07 CST 2015
	 */
	public int updateByPrimaryKeySelective(BaseVo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin_menu
	 * 
	 * @mbggenerated Mon May 18 15:08:07 CST 2015
	 */
	public int updateByPrimaryKey(BaseVo record);

	int updateByExampleSelective(@Param("record") BaseVo record,
			@Param("example") Object example);
}
