package com.mrbt.oa.mvc.vo.source;

import java.math.BigDecimal;
import java.util.Date;

import com.mrbt.oa.mvc.vo.BaseVo;

public class Ths035 extends BaseVo {
	private String f002Ths001;// 基金代码
	private String f003Ths001;// 基金简称
	private String f005Ths001;// 基金全称
	private Short isRecomm;// 是否推荐
	private String f001Ths001;// 内部基金代码

	public String getF002Ths001() {
		return f002Ths001;
	}

	public void setF002Ths001(String f002Ths001) {
		this.f002Ths001 = f002Ths001;
	}

	public String getF003Ths001() {
		return f003Ths001;
	}

	public void setF003Ths001(String f003Ths001) {
		this.f003Ths001 = f003Ths001;
	}

	public String getF005Ths001() {
		return f005Ths001;
	}

	public void setF005Ths001(String f005Ths001) {
		this.f005Ths001 = f005Ths001;
	}

	public Short getIsRecomm() {
		return isRecomm;
	}

	public void setIsRecomm(Short isRecomm) {
		this.isRecomm = isRecomm;
	}

	public String getF001Ths001() {
		return f001Ths001;
	}

	public void setF001Ths001(String f001Ths001) {
		this.f001Ths001 = f001Ths001;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.SEQ
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private BigDecimal seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.CTIME_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private Date ctimeThs035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.RTIME_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private Date rtimeThs035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F001_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f001Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F002_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f002Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F003_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f003Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F004_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private BigDecimal f004Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F005_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private Date f005Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F007_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f007Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F008_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f008Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F011_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f011Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F012_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private Date f012Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F013_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private Date f013Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F014_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f014Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F015_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f015Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F016_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f016Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F017_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f017Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F018_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f018Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F019_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f019Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F020_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f020Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F021_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f021Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F022_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private BigDecimal f022Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F023_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private BigDecimal f023Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F024_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f024Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F025_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private Date f025Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F026_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f026Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F027_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f027Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F028_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f028Ths035;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column THS035.F029_THS035
	 * 
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	private String f029Ths035;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.SEQ
	 * 
	 * @return the value of THS035.SEQ
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public BigDecimal getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.SEQ
	 * 
	 * @param seq
	 *            the value for THS035.SEQ
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setSeq(BigDecimal seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.CTIME_THS035
	 * 
	 * @return the value of THS035.CTIME_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public Date getCtimeThs035() {
		return ctimeThs035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.CTIME_THS035
	 * 
	 * @param ctimeThs035
	 *            the value for THS035.CTIME_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setCtimeThs035(Date ctimeThs035) {
		this.ctimeThs035 = ctimeThs035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.RTIME_THS035
	 * 
	 * @return the value of THS035.RTIME_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public Date getRtimeThs035() {
		return rtimeThs035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.RTIME_THS035
	 * 
	 * @param rtimeThs035
	 *            the value for THS035.RTIME_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setRtimeThs035(Date rtimeThs035) {
		this.rtimeThs035 = rtimeThs035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F001_THS035
	 * 
	 * @return the value of THS035.F001_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF001Ths035() {
		return f001Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F001_THS035
	 * 
	 * @param f001Ths035
	 *            the value for THS035.F001_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF001Ths035(String f001Ths035) {
		this.f001Ths035 = f001Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F002_THS035
	 * 
	 * @return the value of THS035.F002_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF002Ths035() {
		return f002Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F002_THS035
	 * 
	 * @param f002Ths035
	 *            the value for THS035.F002_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF002Ths035(String f002Ths035) {
		this.f002Ths035 = f002Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F003_THS035
	 * 
	 * @return the value of THS035.F003_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF003Ths035() {
		return f003Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F003_THS035
	 * 
	 * @param f003Ths035
	 *            the value for THS035.F003_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF003Ths035(String f003Ths035) {
		this.f003Ths035 = f003Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F004_THS035
	 * 
	 * @return the value of THS035.F004_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public BigDecimal getF004Ths035() {
		return f004Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F004_THS035
	 * 
	 * @param f004Ths035
	 *            the value for THS035.F004_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF004Ths035(BigDecimal f004Ths035) {
		this.f004Ths035 = f004Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F005_THS035
	 * 
	 * @return the value of THS035.F005_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public Date getF005Ths035() {
		return f005Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F005_THS035
	 * 
	 * @param f005Ths035
	 *            the value for THS035.F005_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF005Ths035(Date f005Ths035) {
		this.f005Ths035 = f005Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F007_THS035
	 * 
	 * @return the value of THS035.F007_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF007Ths035() {
		return f007Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F007_THS035
	 * 
	 * @param f007Ths035
	 *            the value for THS035.F007_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF007Ths035(String f007Ths035) {
		this.f007Ths035 = f007Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F008_THS035
	 * 
	 * @return the value of THS035.F008_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF008Ths035() {
		return f008Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F008_THS035
	 * 
	 * @param f008Ths035
	 *            the value for THS035.F008_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF008Ths035(String f008Ths035) {
		this.f008Ths035 = f008Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F011_THS035
	 * 
	 * @return the value of THS035.F011_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF011Ths035() {
		return f011Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F011_THS035
	 * 
	 * @param f011Ths035
	 *            the value for THS035.F011_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF011Ths035(String f011Ths035) {
		this.f011Ths035 = f011Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F012_THS035
	 * 
	 * @return the value of THS035.F012_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public Date getF012Ths035() {
		return f012Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F012_THS035
	 * 
	 * @param f012Ths035
	 *            the value for THS035.F012_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF012Ths035(Date f012Ths035) {
		this.f012Ths035 = f012Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F013_THS035
	 * 
	 * @return the value of THS035.F013_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public Date getF013Ths035() {
		return f013Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F013_THS035
	 * 
	 * @param f013Ths035
	 *            the value for THS035.F013_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF013Ths035(Date f013Ths035) {
		this.f013Ths035 = f013Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F014_THS035
	 * 
	 * @return the value of THS035.F014_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF014Ths035() {
		return f014Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F014_THS035
	 * 
	 * @param f014Ths035
	 *            the value for THS035.F014_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF014Ths035(String f014Ths035) {
		this.f014Ths035 = f014Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F015_THS035
	 * 
	 * @return the value of THS035.F015_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF015Ths035() {
		return f015Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F015_THS035
	 * 
	 * @param f015Ths035
	 *            the value for THS035.F015_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF015Ths035(String f015Ths035) {
		this.f015Ths035 = f015Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F016_THS035
	 * 
	 * @return the value of THS035.F016_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF016Ths035() {
		return f016Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F016_THS035
	 * 
	 * @param f016Ths035
	 *            the value for THS035.F016_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF016Ths035(String f016Ths035) {
		this.f016Ths035 = f016Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F017_THS035
	 * 
	 * @return the value of THS035.F017_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF017Ths035() {
		return f017Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F017_THS035
	 * 
	 * @param f017Ths035
	 *            the value for THS035.F017_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF017Ths035(String f017Ths035) {
		this.f017Ths035 = f017Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F018_THS035
	 * 
	 * @return the value of THS035.F018_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF018Ths035() {
		return f018Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F018_THS035
	 * 
	 * @param f018Ths035
	 *            the value for THS035.F018_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF018Ths035(String f018Ths035) {
		this.f018Ths035 = f018Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F019_THS035
	 * 
	 * @return the value of THS035.F019_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF019Ths035() {
		return f019Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F019_THS035
	 * 
	 * @param f019Ths035
	 *            the value for THS035.F019_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF019Ths035(String f019Ths035) {
		this.f019Ths035 = f019Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F020_THS035
	 * 
	 * @return the value of THS035.F020_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF020Ths035() {
		return f020Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F020_THS035
	 * 
	 * @param f020Ths035
	 *            the value for THS035.F020_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF020Ths035(String f020Ths035) {
		this.f020Ths035 = f020Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F021_THS035
	 * 
	 * @return the value of THS035.F021_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF021Ths035() {
		return f021Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F021_THS035
	 * 
	 * @param f021Ths035
	 *            the value for THS035.F021_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF021Ths035(String f021Ths035) {
		this.f021Ths035 = f021Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F022_THS035
	 * 
	 * @return the value of THS035.F022_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public BigDecimal getF022Ths035() {
		return f022Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F022_THS035
	 * 
	 * @param f022Ths035
	 *            the value for THS035.F022_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF022Ths035(BigDecimal f022Ths035) {
		this.f022Ths035 = f022Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F023_THS035
	 * 
	 * @return the value of THS035.F023_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public BigDecimal getF023Ths035() {
		return f023Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F023_THS035
	 * 
	 * @param f023Ths035
	 *            the value for THS035.F023_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF023Ths035(BigDecimal f023Ths035) {
		this.f023Ths035 = f023Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F024_THS035
	 * 
	 * @return the value of THS035.F024_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF024Ths035() {
		return f024Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F024_THS035
	 * 
	 * @param f024Ths035
	 *            the value for THS035.F024_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF024Ths035(String f024Ths035) {
		this.f024Ths035 = f024Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F025_THS035
	 * 
	 * @return the value of THS035.F025_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public Date getF025Ths035() {
		return f025Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F025_THS035
	 * 
	 * @param f025Ths035
	 *            the value for THS035.F025_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF025Ths035(Date f025Ths035) {
		this.f025Ths035 = f025Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F026_THS035
	 * 
	 * @return the value of THS035.F026_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF026Ths035() {
		return f026Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F026_THS035
	 * 
	 * @param f026Ths035
	 *            the value for THS035.F026_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF026Ths035(String f026Ths035) {
		this.f026Ths035 = f026Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F027_THS035
	 * 
	 * @return the value of THS035.F027_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF027Ths035() {
		return f027Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F027_THS035
	 * 
	 * @param f027Ths035
	 *            the value for THS035.F027_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF027Ths035(String f027Ths035) {
		this.f027Ths035 = f027Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F028_THS035
	 * 
	 * @return the value of THS035.F028_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF028Ths035() {
		return f028Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F028_THS035
	 * 
	 * @param f028Ths035
	 *            the value for THS035.F028_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF028Ths035(String f028Ths035) {
		this.f028Ths035 = f028Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column THS035.F029_THS035
	 * 
	 * @return the value of THS035.F029_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public String getF029Ths035() {
		return f029Ths035;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column THS035.F029_THS035
	 * 
	 * @param f029Ths035
	 *            the value for THS035.F029_THS035
	 * @mbggenerated Mon Jun 20 14:18:02 CST 2016
	 */
	public void setF029Ths035(String f029Ths035) {
		this.f029Ths035 = f029Ths035;
	}
}