package com.mrbt.details.dao;

import java.util.List;

import com.mrbt.details.model.Details;
import com.mrbt.details.model.IndustrAlloca;
import com.mrbt.details.model.ManagersName;
import com.mrbt.details.model.NetValue;
import com.mrbt.details.model.OperatingExpenses;
import com.mrbt.details.model.RateInfo;
import com.mrbt.details.model.ReportingPeriod;

public interface DetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated
     */
    int insert(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THS001
     *
     * @mbggenerated
     */
    int insertSelective(Details record);
    
    /**
     * 通过ID查询基金详情数据
     * @param id
     * @return
     */
	Details getDetailsFromId(String id);

	/**
	 * 通过同花顺内部关键字查询基金经理
	 * @param f001_ths035
	 * @return
	 */
	List<ManagersName> findFundManagersName(String f001_ths035);

	/**
	 * 行业配置柱状图、列表
	 * @param stateDate
	 * @param endDate
	 * @param id
	 * @return
	 */
	List<IndustrAlloca> getIndustrAlloca(String stateDate, String endDate, String id);

	/**
	 * 净值、累计净值曲线
	 * @param param
	 * @return
	 */
	List<NetValue> getNetValueList(NetValue param);

	/**
	 * 查询行业配置年份列表
	 * @param id
	 * @return
	 */
	List<String> getIndustAllocaYear(String id);

	/**
	 * 查询基金经理基本信息
	 * @param funds_code
	 * @return
	 */
	List<ManagersName> getManagerBaseInfo(String funds_code);
	
	/**
	 * 查询基金经理经历信息
	 * @param id
	 * @return
	 */
	List<ManagersName> getManagerExperience(String id);

	double getNewNetValue(String fundsCode);

	double getOldNetValue(String fundsCode, String date);

	List<ReportingPeriod> getReportingPeriod(String id);

	double netValueFromDataCode(String thsKey, String reportDate);

	List<RateInfo> getRateInfo(String id);

	List<RateInfo> getRateInfo2(String id);

	OperatingExpenses getOperatingExpenses(String id);
    
}