package com.mrbt.oa.mvc.mapper.funds;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.funds.FundsPackageCurve;
import com.mrbt.oa.mvc.vo.funds.FundsPackageCurveExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FundsPackageCurveMapper extends BaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_PACKAGE_CURVE
	 *
	 * @mbggenerated Fri Jul 01 16:01:30 CST 2016
	 */
	int countByExample(FundsPackageCurveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_PACKAGE_CURVE
	 *
	 * @mbggenerated Fri Jul 01 16:01:30 CST 2016
	 */
	int deleteByExample(FundsPackageCurveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_PACKAGE_CURVE
	 *
	 * @mbggenerated Fri Jul 01 16:01:30 CST 2016
	 */
	int insert(FundsPackageCurve record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_PACKAGE_CURVE
	 *
	 * @mbggenerated Fri Jul 01 16:01:30 CST 2016
	 */
	int insertSelective(FundsPackageCurve record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_PACKAGE_CURVE
	 *
	 * @mbggenerated Fri Jul 01 16:01:30 CST 2016
	 */
	List<FundsPackageCurve> selectByExample(FundsPackageCurveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_PACKAGE_CURVE
	 *
	 * @mbggenerated Fri Jul 01 16:01:30 CST 2016
	 */
	int updateByExampleSelective(@Param("record") FundsPackageCurve record,
			@Param("example") FundsPackageCurveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_PACKAGE_CURVE
	 *
	 * @mbggenerated Fri Jul 01 16:01:30 CST 2016
	 */
	int updateByExample(@Param("record") FundsPackageCurve record,
			@Param("example") FundsPackageCurveExample example);

	int batchInsertFundsPackageCurve(List<FundsPackageCurve> datas);

}