package com.mrbt.oa.mvc.mapper.funds;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.funds.FundsTheme;
import com.mrbt.oa.mvc.vo.funds.FundsThemeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundsThemeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int countByExample(FundsThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int deleteByExample(FundsThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int insert(FundsTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int insertSelective(FundsTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    List<FundsTheme> selectByExample(FundsThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    FundsTheme selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") FundsTheme record, @Param("example") FundsThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int updateByExample(@Param("record") FundsTheme record, @Param("example") FundsThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int updateByPrimaryKeySelective(FundsTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_THEME
     *
     * @mbggenerated Thu Jul 07 13:45:45 CST 2016
     */
    int updateByPrimaryKey(FundsTheme record);
}