package com.mrbt.oa.mvc.mapper.funds;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.funds.FundsKnowledge;
import com.mrbt.oa.mvc.vo.funds.FundsKnowledgeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundsKnowledgeMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int countByExample(FundsKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int deleteByExample(FundsKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int insert(FundsKnowledge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int insertSelective(FundsKnowledge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	List<FundsKnowledge> selectByExample(FundsKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	FundsKnowledge selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int updateByExampleSelective(@Param("record") FundsKnowledge record,
			@Param("example") FundsKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int updateByExample(@Param("record") FundsKnowledge record,
			@Param("example") FundsKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int updateByPrimaryKeySelective(FundsKnowledge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_KNOWLEDGE
	 * @mbggenerated  Mon Jul 11 18:09:22 CST 2016
	 */
	int updateByPrimaryKey(FundsKnowledge record);
}