package com.mrbt.oa.mvc.mapper.funds;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.funds.FundsBaseType;
import com.mrbt.oa.mvc.vo.funds.FundsBaseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundsBaseTypeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int countByExample(FundsBaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int deleteByExample(FundsBaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int insert(FundsBaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int insertSelective(FundsBaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    List<FundsBaseType> selectByExample(FundsBaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    FundsBaseType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") FundsBaseType record, @Param("example") FundsBaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int updateByExample(@Param("record") FundsBaseType record, @Param("example") FundsBaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int updateByPrimaryKeySelective(FundsBaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNDS_BASE_TYPE
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    int updateByPrimaryKey(FundsBaseType record);
}