package com.mrbt.oa.mvc.mapper.funds;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.funds.FundsRisk;
import com.mrbt.oa.mvc.vo.funds.FundsRiskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundsRiskMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_RISK
	 * 
	 * @mbggenerated Fri Jul 01 14:18:29 CST 2016
	 */
	int countByExample(FundsRiskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_RISK
	 * 
	 * @mbggenerated Fri Jul 01 14:18:29 CST 2016
	 */
	int deleteByExample(FundsRiskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_RISK
	 * 
	 * @mbggenerated Fri Jul 01 14:18:29 CST 2016
	 */
	int insert(FundsRisk record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_RISK
	 * 
	 * @mbggenerated Fri Jul 01 14:18:29 CST 2016
	 */
	int insertSelective(FundsRisk record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_RISK
	 * 
	 * @mbggenerated Fri Jul 01 14:18:29 CST 2016
	 */
	List<FundsRisk> selectByExample(FundsRiskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_RISK
	 * 
	 * @mbggenerated Fri Jul 01 14:18:29 CST 2016
	 */
	int updateByExampleSelective(@Param("record") FundsRisk record,
			@Param("example") FundsRiskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table FUNDS_RISK
	 * 
	 * @mbggenerated Fri Jul 01 14:18:29 CST 2016
	 */
	int updateByExample(@Param("record") FundsRisk record,
			@Param("example") FundsRiskExample example);

	int batchInsertFundsRisk(List<FundsRisk> datas);
}