package com.mrbt.oa.mvc.mapper.funds;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.funds.FundsMarketLog;
import com.mrbt.oa.mvc.vo.funds.FundsMarketLogExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundsMarketLogMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int countByExample(FundsMarketLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int deleteByExample(FundsMarketLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int insert(FundsMarketLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int insertSelective(FundsMarketLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	List<FundsMarketLog> selectByExample(FundsMarketLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	FundsMarketLog selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int updateByExampleSelective(@Param("record") FundsMarketLog record,
			@Param("example") FundsMarketLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int updateByExample(@Param("record") FundsMarketLog record,
			@Param("example") FundsMarketLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int updateByPrimaryKeySelective(FundsMarketLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_MARKET_LOG
	 * @mbggenerated  Wed Jun 29 11:28:13 CST 2016
	 */
	int updateByPrimaryKey(FundsMarketLog record);
}