package com.mrbt.oa.mvc.mapper.funds;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.funds.FundsPackageRatio;
import com.mrbt.oa.mvc.vo.funds.FundsPackageRatioExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;

public interface FundsPackageRatioMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int countByExample(FundsPackageRatioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int deleteByExample(FundsPackageRatioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int insert(FundsPackageRatio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int insertSelective(FundsPackageRatio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	List<FundsPackageRatio> selectByExample(FundsPackageRatioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	FundsPackageRatio selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int updateByExampleSelective(@Param("record") FundsPackageRatio record,
			@Param("example") FundsPackageRatioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int updateByExample(@Param("record") FundsPackageRatio record,
			@Param("example") FundsPackageRatioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int updateByPrimaryKeySelective(FundsPackageRatio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	int updateByPrimaryKey(FundsPackageRatio record);

	List<FundsPackageRatio> findByFundsCodeAndTypeId(Map map);

	int findByFundsCodeNoId(Map map);
	
	List<String> findByDistinctFundsTypeId(BigDecimal typeId);
	
}