package com.mrbt.oa.mvc.mapper.source;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.source.Ths043;
import com.mrbt.oa.mvc.vo.source.Ths043Example;

public interface Ths043Mapper extends BaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table THS043
	 *
	 * @mbggenerated Fri Jul 01 15:40:56 CST 2016
	 */
	int countByExample(Ths043Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table THS043
	 *
	 * @mbggenerated Fri Jul 01 15:40:56 CST 2016
	 */
	int deleteByExample(Ths043Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table THS043
	 *
	 * @mbggenerated Fri Jul 01 15:40:56 CST 2016
	 */
	int insert(Ths043 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table THS043
	 *
	 * @mbggenerated Fri Jul 01 15:40:56 CST 2016
	 */
	int insertSelective(Ths043 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table THS043
	 *
	 * @mbggenerated Fri Jul 01 15:40:56 CST 2016
	 */
	List<Ths043> selectByExample(Ths043Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table THS043
	 *
	 * @mbggenerated Fri Jul 01 15:40:56 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Ths043 record,
			@Param("example") Ths043Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table THS043
	 *
	 * @mbggenerated Fri Jul 01 15:40:56 CST 2016
	 */
	int updateByExample(@Param("record") Ths043 record,
			@Param("example") Ths043Example example);

}