package com.mrbt.oa.mvc.vo.company;

import com.mrbt.oa.mvc.vo.BaseVo;

public class MrbtCompanyUserProperties extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_PROPERTIES.ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_PROPERTIES.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_PROPERTIES.USER_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_PROPERTIES.USER_MOBILE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_PROPERTIES.USER_MAIL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_PROPERTIES.USER_QQ
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String userQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_PROPERTIES.USER_BIRTHDY
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String userBirthdy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_PROPERTIES.ID
     *
     * @return the value of MRBT_COMPANY_USER_PROPERTIES.ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_PROPERTIES.ID
     *
     * @param id the value for MRBT_COMPANY_USER_PROPERTIES.ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_PROPERTIES.U_ID
     *
     * @return the value of MRBT_COMPANY_USER_PROPERTIES.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_PROPERTIES.U_ID
     *
     * @param uId the value for MRBT_COMPANY_USER_PROPERTIES.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_NAME
     *
     * @return the value of MRBT_COMPANY_USER_PROPERTIES.USER_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_NAME
     *
     * @param userName the value for MRBT_COMPANY_USER_PROPERTIES.USER_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_MOBILE
     *
     * @return the value of MRBT_COMPANY_USER_PROPERTIES.USER_MOBILE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_MOBILE
     *
     * @param userMobile the value for MRBT_COMPANY_USER_PROPERTIES.USER_MOBILE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_MAIL
     *
     * @return the value of MRBT_COMPANY_USER_PROPERTIES.USER_MAIL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_MAIL
     *
     * @param userMail the value for MRBT_COMPANY_USER_PROPERTIES.USER_MAIL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_QQ
     *
     * @return the value of MRBT_COMPANY_USER_PROPERTIES.USER_QQ
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getUserQq() {
        return userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_QQ
     *
     * @param userQq the value for MRBT_COMPANY_USER_PROPERTIES.USER_QQ
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setUserQq(String userQq) {
        this.userQq = userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_BIRTHDY
     *
     * @return the value of MRBT_COMPANY_USER_PROPERTIES.USER_BIRTHDY
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getUserBirthdy() {
        return userBirthdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_PROPERTIES.USER_BIRTHDY
     *
     * @param userBirthdy the value for MRBT_COMPANY_USER_PROPERTIES.USER_BIRTHDY
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setUserBirthdy(String userBirthdy) {
        this.userBirthdy = userBirthdy;
    }
}