package com.mrbt.oa.mvc.vo.company;

import com.mrbt.oa.mvc.vo.BaseVo;

public class MrbtCompanyUserRDepart extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_R_DEPART.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_R_DEPART.DP_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer dpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_R_DEPART.IS_LEADER
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer isLeader;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_R_DEPART.U_ID
     *
     * @return the value of MRBT_COMPANY_USER_R_DEPART.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_R_DEPART.U_ID
     *
     * @param uId the value for MRBT_COMPANY_USER_R_DEPART.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_R_DEPART.DP_ID
     *
     * @return the value of MRBT_COMPANY_USER_R_DEPART.DP_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getDpId() {
        return dpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_R_DEPART.DP_ID
     *
     * @param dpId the value for MRBT_COMPANY_USER_R_DEPART.DP_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setDpId(Integer dpId) {
        this.dpId = dpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_R_DEPART.IS_LEADER
     *
     * @return the value of MRBT_COMPANY_USER_R_DEPART.IS_LEADER
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getIsLeader() {
        return isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_R_DEPART.IS_LEADER
     *
     * @param isLeader the value for MRBT_COMPANY_USER_R_DEPART.IS_LEADER
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setIsLeader(Integer isLeader) {
        this.isLeader = isLeader;
    }
}