package com.mrbt.oa.mvc.vo.company;

import com.mrbt.oa.mvc.vo.BaseVo;

public class MrbtCompanyMenu extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.MENU_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.PARENT_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.URL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.TEXT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.ACTION_EVENT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String actionEvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.ICON
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.SEQ
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU.TYPE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.ID
     *
     * @return the value of MRBT_COMPANY_MENU.ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.ID
     *
     * @param id the value for MRBT_COMPANY_MENU.ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.MENU_NAME
     *
     * @return the value of MRBT_COMPANY_MENU.MENU_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.MENU_NAME
     *
     * @param menuName the value for MRBT_COMPANY_MENU.MENU_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.PARENT_ID
     *
     * @return the value of MRBT_COMPANY_MENU.PARENT_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.PARENT_ID
     *
     * @param parentId the value for MRBT_COMPANY_MENU.PARENT_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.URL
     *
     * @return the value of MRBT_COMPANY_MENU.URL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.URL
     *
     * @param url the value for MRBT_COMPANY_MENU.URL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.TEXT
     *
     * @return the value of MRBT_COMPANY_MENU.TEXT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.TEXT
     *
     * @param text the value for MRBT_COMPANY_MENU.TEXT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.ACTION_EVENT
     *
     * @return the value of MRBT_COMPANY_MENU.ACTION_EVENT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getActionEvent() {
        return actionEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.ACTION_EVENT
     *
     * @param actionEvent the value for MRBT_COMPANY_MENU.ACTION_EVENT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setActionEvent(String actionEvent) {
        this.actionEvent = actionEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.ICON
     *
     * @return the value of MRBT_COMPANY_MENU.ICON
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.ICON
     *
     * @param icon the value for MRBT_COMPANY_MENU.ICON
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.SEQ
     *
     * @return the value of MRBT_COMPANY_MENU.SEQ
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.SEQ
     *
     * @param seq the value for MRBT_COMPANY_MENU.SEQ
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU.TYPE
     *
     * @return the value of MRBT_COMPANY_MENU.TYPE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU.TYPE
     *
     * @param type the value for MRBT_COMPANY_MENU.TYPE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }
}