package com.mrbt.oa.mvc.vo.company;

import com.mrbt.oa.mvc.vo.BaseVo;

public class MrbtCompanyMenuRRole extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU_R_ROLE.R_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU_R_ROLE.MENU_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU_R_ROLE.MENU_URL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU_R_ROLE.R_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_MENU_R_ROLE.ACTION_EVENT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private String actionEvent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU_R_ROLE.R_ID
     *
     * @return the value of MRBT_COMPANY_MENU_R_ROLE.R_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU_R_ROLE.R_ID
     *
     * @param rId the value for MRBT_COMPANY_MENU_R_ROLE.R_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU_R_ROLE.MENU_ID
     *
     * @return the value of MRBT_COMPANY_MENU_R_ROLE.MENU_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU_R_ROLE.MENU_ID
     *
     * @param menuId the value for MRBT_COMPANY_MENU_R_ROLE.MENU_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU_R_ROLE.MENU_URL
     *
     * @return the value of MRBT_COMPANY_MENU_R_ROLE.MENU_URL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU_R_ROLE.MENU_URL
     *
     * @param menuUrl the value for MRBT_COMPANY_MENU_R_ROLE.MENU_URL
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU_R_ROLE.R_NAME
     *
     * @return the value of MRBT_COMPANY_MENU_R_ROLE.R_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU_R_ROLE.R_NAME
     *
     * @param rName the value for MRBT_COMPANY_MENU_R_ROLE.R_NAME
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setrName(String rName) {
        this.rName = rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_MENU_R_ROLE.ACTION_EVENT
     *
     * @return the value of MRBT_COMPANY_MENU_R_ROLE.ACTION_EVENT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public String getActionEvent() {
        return actionEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_MENU_R_ROLE.ACTION_EVENT
     *
     * @param actionEvent the value for MRBT_COMPANY_MENU_R_ROLE.ACTION_EVENT
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setActionEvent(String actionEvent) {
        this.actionEvent = actionEvent;
    }
}