package com.mrbt.oa.mvc.vo.company;

import com.mrbt.oa.mvc.vo.BaseVo;
import java.math.BigDecimal;

public class MrbtAttachment extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.ID
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.FILE_NAME
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.FILE_TYPE
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.FILE_SIZE
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private BigDecimal fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.PATH
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.CREATER
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private Integer creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.DOWN_TIMES
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private Integer downTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.VISITOR
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private Integer visitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.REMARK
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_ATTACHMENT.STATUS
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.ID
     *
     * @return the value of MRBT_ATTACHMENT.ID
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.ID
     *
     * @param id the value for MRBT_ATTACHMENT.ID
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.FILE_NAME
     *
     * @return the value of MRBT_ATTACHMENT.FILE_NAME
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.FILE_NAME
     *
     * @param fileName the value for MRBT_ATTACHMENT.FILE_NAME
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.FILE_TYPE
     *
     * @return the value of MRBT_ATTACHMENT.FILE_TYPE
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.FILE_TYPE
     *
     * @param fileType the value for MRBT_ATTACHMENT.FILE_TYPE
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.FILE_SIZE
     *
     * @return the value of MRBT_ATTACHMENT.FILE_SIZE
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public BigDecimal getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.FILE_SIZE
     *
     * @param fileSize the value for MRBT_ATTACHMENT.FILE_SIZE
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setFileSize(BigDecimal fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.DESCRIPTION
     *
     * @return the value of MRBT_ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.DESCRIPTION
     *
     * @param description the value for MRBT_ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.PATH
     *
     * @return the value of MRBT_ATTACHMENT.PATH
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.PATH
     *
     * @param path the value for MRBT_ATTACHMENT.PATH
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.CREATER
     *
     * @return the value of MRBT_ATTACHMENT.CREATER
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.CREATER
     *
     * @param creater the value for MRBT_ATTACHMENT.CREATER
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.DOWN_TIMES
     *
     * @return the value of MRBT_ATTACHMENT.DOWN_TIMES
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public Integer getDownTimes() {
        return downTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.DOWN_TIMES
     *
     * @param downTimes the value for MRBT_ATTACHMENT.DOWN_TIMES
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setDownTimes(Integer downTimes) {
        this.downTimes = downTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.VISITOR
     *
     * @return the value of MRBT_ATTACHMENT.VISITOR
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public Integer getVisitor() {
        return visitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.VISITOR
     *
     * @param visitor the value for MRBT_ATTACHMENT.VISITOR
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setVisitor(Integer visitor) {
        this.visitor = visitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.REMARK
     *
     * @return the value of MRBT_ATTACHMENT.REMARK
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.REMARK
     *
     * @param remark the value for MRBT_ATTACHMENT.REMARK
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_ATTACHMENT.STATUS
     *
     * @return the value of MRBT_ATTACHMENT.STATUS
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_ATTACHMENT.STATUS
     *
     * @param status the value for MRBT_ATTACHMENT.STATUS
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}