package com.mrbt.oa.mvc.vo.company;

import java.util.List;

import com.mrbt.oa.mvc.vo.BaseVo;

public class MrbtCompanyUserRRole extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_R_ROLE.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MRBT_COMPANY_USER_R_ROLE.R_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    private Integer rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_R_ROLE.U_ID
     *
     * @return the value of MRBT_COMPANY_USER_R_ROLE.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_R_ROLE.U_ID
     *
     * @param uId the value for MRBT_COMPANY_USER_R_ROLE.U_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MRBT_COMPANY_USER_R_ROLE.R_ID
     *
     * @return the value of MRBT_COMPANY_USER_R_ROLE.R_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MRBT_COMPANY_USER_R_ROLE.R_ID
     *
     * @param rId the value for MRBT_COMPANY_USER_R_ROLE.R_ID
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }
    
	// ==============zi ding yi
	public List<MrbtCompanyRole> rolse;

	public List<MrbtCompanyRole> getRolse() {
		return rolse;
	}

	public void setRolse(List<MrbtCompanyRole> rolse) {
		this.rolse = rolse;
	}
}