package com.mrbt.oa.mvc.mapper.company;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.company.MrbtCompanyRole;
import com.mrbt.oa.mvc.vo.company.MrbtCompanyRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MrbtCompanyRoleMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int countByExample(MrbtCompanyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int deleteByExample(MrbtCompanyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int insert(MrbtCompanyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int insertSelective(MrbtCompanyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    List<MrbtCompanyRole> selectByExample(MrbtCompanyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    MrbtCompanyRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") MrbtCompanyRole record, @Param("example") MrbtCompanyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int updateByExample(@Param("record") MrbtCompanyRole record, @Param("example") MrbtCompanyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int updateByPrimaryKeySelective(MrbtCompanyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int updateByPrimaryKey(MrbtCompanyRole record);
}