package com.mrbt.oa.mvc.mapper.company;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.company.MrbtCompanyUserRRole;
import com.mrbt.oa.mvc.vo.company.MrbtCompanyUserRRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MrbtCompanyUserRRoleMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int countByExample(MrbtCompanyUserRRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int deleteByExample(MrbtCompanyUserRRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int insert(MrbtCompanyUserRRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int insertSelective(MrbtCompanyUserRRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    List<MrbtCompanyUserRRole> selectByExample(MrbtCompanyUserRRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") MrbtCompanyUserRRole record, @Param("example") MrbtCompanyUserRRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_ROLE
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int updateByExample(@Param("record") MrbtCompanyUserRRole record, @Param("example") MrbtCompanyUserRRoleExample example);
}