package com.mrbt.oa.mvc.mapper.company;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.company.MrbtCompanyUserRDepart;
import com.mrbt.oa.mvc.vo.company.MrbtCompanyUserRDepartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MrbtCompanyUserRDepartMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_DEPART
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int countByExample(MrbtCompanyUserRDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_DEPART
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int deleteByExample(MrbtCompanyUserRDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_DEPART
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int insert(MrbtCompanyUserRDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_DEPART
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int insertSelective(MrbtCompanyUserRDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_DEPART
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    List<MrbtCompanyUserRDepart> selectByExample(MrbtCompanyUserRDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_DEPART
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") MrbtCompanyUserRDepart record, @Param("example") MrbtCompanyUserRDepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_COMPANY_USER_R_DEPART
     *
     * @mbggenerated Thu May 12 15:09:23 CST 2016
     */
    int updateByExample(@Param("record") MrbtCompanyUserRDepart record, @Param("example") MrbtCompanyUserRDepartExample example);
}