package com.mrbt.oa.mvc.mapper.company;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.company.MrbtCompanyConfig;
import com.mrbt.oa.mvc.vo.company.MrbtCompanyConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MrbtCompanyConfigMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int countByExample(MrbtCompanyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int deleteByExample(MrbtCompanyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int insert(MrbtCompanyConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int insertSelective(MrbtCompanyConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	List<MrbtCompanyConfig> selectByExample(MrbtCompanyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	MrbtCompanyConfig selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") MrbtCompanyConfig record,
			@Param("example") MrbtCompanyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int updateByExample(@Param("record") MrbtCompanyConfig record,
			@Param("example") MrbtCompanyConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int updateByPrimaryKeySelective(MrbtCompanyConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MRBT_COMPANY_CONFIG
	 * @mbggenerated  Wed Jun 01 09:29:20 CST 2016
	 */
	int updateByPrimaryKey(MrbtCompanyConfig record);
}