package com.mrbt.oa.mvc.mapper.company;

import com.mrbt.oa.mvc.mapper.BaseMapper;
import com.mrbt.oa.mvc.vo.company.MrbtAttachment;
import com.mrbt.oa.mvc.vo.company.MrbtAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MrbtAttachmentMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int countByExample(MrbtAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int deleteByExample(MrbtAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int insert(MrbtAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int insertSelective(MrbtAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    List<MrbtAttachment> selectByExample(MrbtAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    MrbtAttachment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") MrbtAttachment record, @Param("example") MrbtAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int updateByExample(@Param("record") MrbtAttachment record, @Param("example") MrbtAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int updateByPrimaryKeySelective(MrbtAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MRBT_ATTACHMENT
     *
     * @mbggenerated Thu May 26 11:38:25 CST 2016
     */
    int updateByPrimaryKey(MrbtAttachment record);
}