package com.mrbt.oa.mvc.vo.funds;

import com.mrbt.oa.mvc.vo.BaseExample;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FundsPackageTypeExample extends BaseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public FundsPackageTypeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(BigDecimal value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(BigDecimal value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(BigDecimal value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(BigDecimal value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<BigDecimal> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<BigDecimal> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andFeatureIsNull() {
			addCriterion("FEATURE is null");
			return (Criteria) this;
		}

		public Criteria andFeatureIsNotNull() {
			addCriterion("FEATURE is not null");
			return (Criteria) this;
		}

		public Criteria andFeatureEqualTo(String value) {
			addCriterion("FEATURE =", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotEqualTo(String value) {
			addCriterion("FEATURE <>", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureGreaterThan(String value) {
			addCriterion("FEATURE >", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureGreaterThanOrEqualTo(String value) {
			addCriterion("FEATURE >=", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLessThan(String value) {
			addCriterion("FEATURE <", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLessThanOrEqualTo(String value) {
			addCriterion("FEATURE <=", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureLike(String value) {
			addCriterion("FEATURE like", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotLike(String value) {
			addCriterion("FEATURE not like", value, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureIn(List<String> values) {
			addCriterion("FEATURE in", values, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotIn(List<String> values) {
			addCriterion("FEATURE not in", values, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureBetween(String value1, String value2) {
			addCriterion("FEATURE between", value1, value2, "feature");
			return (Criteria) this;
		}

		public Criteria andFeatureNotBetween(String value1, String value2) {
			addCriterion("FEATURE not between", value1, value2, "feature");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeIsNull() {
			addCriterion("CONF_ANALYZE is null");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeIsNotNull() {
			addCriterion("CONF_ANALYZE is not null");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeEqualTo(String value) {
			addCriterion("CONF_ANALYZE =", value, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeNotEqualTo(String value) {
			addCriterion("CONF_ANALYZE <>", value, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeGreaterThan(String value) {
			addCriterion("CONF_ANALYZE >", value, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeGreaterThanOrEqualTo(String value) {
			addCriterion("CONF_ANALYZE >=", value, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeLessThan(String value) {
			addCriterion("CONF_ANALYZE <", value, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeLessThanOrEqualTo(String value) {
			addCriterion("CONF_ANALYZE <=", value, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeLike(String value) {
			addCriterion("CONF_ANALYZE like", value, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeNotLike(String value) {
			addCriterion("CONF_ANALYZE not like", value, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeIn(List<String> values) {
			addCriterion("CONF_ANALYZE in", values, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeNotIn(List<String> values) {
			addCriterion("CONF_ANALYZE not in", values, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeBetween(String value1, String value2) {
			addCriterion("CONF_ANALYZE between", value1, value2, "confAnalyze");
			return (Criteria) this;
		}

		public Criteria andConfAnalyzeNotBetween(String value1, String value2) {
			addCriterion("CONF_ANALYZE not between", value1, value2,
					"confAnalyze");
			return (Criteria) this;
		}

		public Criteria andOnLineIsNull() {
			addCriterion("ON_LINE is null");
			return (Criteria) this;
		}

		public Criteria andOnLineIsNotNull() {
			addCriterion("ON_LINE is not null");
			return (Criteria) this;
		}

		public Criteria andOnLineEqualTo(Short value) {
			addCriterion("ON_LINE =", value, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineNotEqualTo(Short value) {
			addCriterion("ON_LINE <>", value, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineGreaterThan(Short value) {
			addCriterion("ON_LINE >", value, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineGreaterThanOrEqualTo(Short value) {
			addCriterion("ON_LINE >=", value, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineLessThan(Short value) {
			addCriterion("ON_LINE <", value, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineLessThanOrEqualTo(Short value) {
			addCriterion("ON_LINE <=", value, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineIn(List<Short> values) {
			addCriterion("ON_LINE in", values, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineNotIn(List<Short> values) {
			addCriterion("ON_LINE not in", values, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineBetween(Short value1, Short value2) {
			addCriterion("ON_LINE between", value1, value2, "onLine");
			return (Criteria) this;
		}

		public Criteria andOnLineNotBetween(Short value1, Short value2) {
			addCriterion("ON_LINE not between", value1, value2, "onLine");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table FUNDS_PACKAGE_TYPE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FUNDS_PACKAGE_TYPE
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 29 15:49:10 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}