package com.mrbt.oa.mvc.vo.funds;

import com.mrbt.oa.mvc.vo.BaseVo;
import java.math.BigDecimal;

public class FundsPackageRatio extends BaseVo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_RATIO.ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_RATIO.TYPE_ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	private BigDecimal typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_RATIO.TYPE_NAME
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_RATIO.FUNDS_CODE
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	private String fundsCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_RATIO.RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	private BigDecimal ratio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_RATIO.FUNDS_CODE_INNER
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	private String fundsCodeInner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_RATIO.FUNDS_TYPE_ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	private String fundsTypeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_RATIO.ID
	 * @return  the value of FUNDS_PACKAGE_RATIO.ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_RATIO.ID
	 * @param id  the value for FUNDS_PACKAGE_RATIO.ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_RATIO.TYPE_ID
	 * @return  the value of FUNDS_PACKAGE_RATIO.TYPE_ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public BigDecimal getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_RATIO.TYPE_ID
	 * @param typeId  the value for FUNDS_PACKAGE_RATIO.TYPE_ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public void setTypeId(BigDecimal typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_RATIO.TYPE_NAME
	 * @return  the value of FUNDS_PACKAGE_RATIO.TYPE_NAME
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_RATIO.TYPE_NAME
	 * @param typeName  the value for FUNDS_PACKAGE_RATIO.TYPE_NAME
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_RATIO.FUNDS_CODE
	 * @return  the value of FUNDS_PACKAGE_RATIO.FUNDS_CODE
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public String getFundsCode() {
		return fundsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_RATIO.FUNDS_CODE
	 * @param fundsCode  the value for FUNDS_PACKAGE_RATIO.FUNDS_CODE
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public void setFundsCode(String fundsCode) {
		this.fundsCode = fundsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_RATIO.RATIO
	 * @return  the value of FUNDS_PACKAGE_RATIO.RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public BigDecimal getRatio() {
		return ratio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_RATIO.RATIO
	 * @param ratio  the value for FUNDS_PACKAGE_RATIO.RATIO
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public void setRatio(BigDecimal ratio) {
		this.ratio = ratio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_RATIO.FUNDS_CODE_INNER
	 * @return  the value of FUNDS_PACKAGE_RATIO.FUNDS_CODE_INNER
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public String getFundsCodeInner() {
		return fundsCodeInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_RATIO.FUNDS_CODE_INNER
	 * @param fundsCodeInner  the value for FUNDS_PACKAGE_RATIO.FUNDS_CODE_INNER
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public void setFundsCodeInner(String fundsCodeInner) {
		this.fundsCodeInner = fundsCodeInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_RATIO.FUNDS_TYPE_ID
	 * @return  the value of FUNDS_PACKAGE_RATIO.FUNDS_TYPE_ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public String getFundsTypeId() {
		return fundsTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_RATIO.FUNDS_TYPE_ID
	 * @param fundsTypeId  the value for FUNDS_PACKAGE_RATIO.FUNDS_TYPE_ID
	 * @mbggenerated  Fri Jul 08 14:31:33 CST 2016
	 */
	public void setFundsTypeId(String fundsTypeId) {
		this.fundsTypeId = fundsTypeId;
	}

	@Override
	public String toString() {
		return "FundsPackageRatio [id=" + id + ", typeId=" + typeId
				+ ", typeName=" + typeName + ", fundsCode=" + fundsCode
				+ ", ratio=" + ratio + ", fundsTypeId=" + fundsTypeId
				+ ", fundsCodeInner=" + fundsCodeInner + "]";
	}

}