package com.mrbt.oa.mvc.vo.funds;

import com.mrbt.oa.mvc.vo.BaseVo;

public class FundsBaseType extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNDS_BASE_TYPE.ID
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNDS_BASE_TYPE.NAME
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNDS_BASE_TYPE.ID
     *
     * @return the value of FUNDS_BASE_TYPE.ID
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNDS_BASE_TYPE.ID
     *
     * @param id the value for FUNDS_BASE_TYPE.ID
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNDS_BASE_TYPE.NAME
     *
     * @return the value of FUNDS_BASE_TYPE.NAME
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNDS_BASE_TYPE.NAME
     *
     * @param name the value for FUNDS_BASE_TYPE.NAME
     *
     * @mbggenerated Thu Jun 30 14:59:33 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}