package com.mrbt.oa.mvc.vo.funds;

import com.mrbt.oa.mvc.vo.BaseVo;
import java.math.BigDecimal;
import java.util.Date;

public class FundsPackageType extends BaseVo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_TYPE.ID
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_TYPE.NAME
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_TYPE.CREATE_TIME
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_TYPE.FEATURE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	private String feature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_TYPE.CONF_ANALYZE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	private String confAnalyze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FUNDS_PACKAGE_TYPE.ON_LINE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	private Short onLine;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_TYPE.ID
	 * @return  the value of FUNDS_PACKAGE_TYPE.ID
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_TYPE.ID
	 * @param id  the value for FUNDS_PACKAGE_TYPE.ID
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_TYPE.NAME
	 * @return  the value of FUNDS_PACKAGE_TYPE.NAME
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_TYPE.NAME
	 * @param name  the value for FUNDS_PACKAGE_TYPE.NAME
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_TYPE.CREATE_TIME
	 * @return  the value of FUNDS_PACKAGE_TYPE.CREATE_TIME
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_TYPE.CREATE_TIME
	 * @param createTime  the value for FUNDS_PACKAGE_TYPE.CREATE_TIME
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_TYPE.FEATURE
	 * @return  the value of FUNDS_PACKAGE_TYPE.FEATURE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public String getFeature() {
		return feature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_TYPE.FEATURE
	 * @param feature  the value for FUNDS_PACKAGE_TYPE.FEATURE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void setFeature(String feature) {
		this.feature = feature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_TYPE.CONF_ANALYZE
	 * @return  the value of FUNDS_PACKAGE_TYPE.CONF_ANALYZE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public String getConfAnalyze() {
		return confAnalyze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_TYPE.CONF_ANALYZE
	 * @param confAnalyze  the value for FUNDS_PACKAGE_TYPE.CONF_ANALYZE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void setConfAnalyze(String confAnalyze) {
		this.confAnalyze = confAnalyze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FUNDS_PACKAGE_TYPE.ON_LINE
	 * @return  the value of FUNDS_PACKAGE_TYPE.ON_LINE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public Short getOnLine() {
		return onLine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FUNDS_PACKAGE_TYPE.ON_LINE
	 * @param onLine  the value for FUNDS_PACKAGE_TYPE.ON_LINE
	 * @mbggenerated  Wed Jul 06 15:50:40 CST 2016
	 */
	public void setOnLine(Short onLine) {
		this.onLine = onLine;
	}
}