package com.mrbt.oa.mvc.vo.funds;

import com.mrbt.oa.mvc.vo.BaseVo;
import java.math.BigDecimal;
import java.util.Date;

public class FundsPackageCurve extends BaseVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNDS_PACKAGE_CURVE.TYPE_ID
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    private BigDecimal typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNDS_PACKAGE_CURVE.C_DATE
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    private Date cDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNDS_PACKAGE_CURVE.C_DATA
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    private BigDecimal cData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNDS_PACKAGE_CURVE.TYPE_ID
     *
     * @return the value of FUNDS_PACKAGE_CURVE.TYPE_ID
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    public BigDecimal getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNDS_PACKAGE_CURVE.TYPE_ID
     *
     * @param typeId the value for FUNDS_PACKAGE_CURVE.TYPE_ID
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    public void setTypeId(BigDecimal typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNDS_PACKAGE_CURVE.C_DATE
     *
     * @return the value of FUNDS_PACKAGE_CURVE.C_DATE
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    public Date getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNDS_PACKAGE_CURVE.C_DATE
     *
     * @param cDate the value for FUNDS_PACKAGE_CURVE.C_DATE
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    public void setcDate(Date cDate) {
        this.cDate = cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNDS_PACKAGE_CURVE.C_DATA
     *
     * @return the value of FUNDS_PACKAGE_CURVE.C_DATA
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    public BigDecimal getcData() {
        return cData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNDS_PACKAGE_CURVE.C_DATA
     *
     * @param cData the value for FUNDS_PACKAGE_CURVE.C_DATA
     *
     * @mbggenerated Fri Jul 01 16:01:30 CST 2016
     */
    public void setcData(BigDecimal cData) {
        this.cData = cData;
    }

	@Override
	public String toString() {
		return "FundsPackageCurve [typeId=" + typeId + ", cDate=" + cDate
				+ ", cData=" + cData + "]";
	}
    
    
}